(function () {
  'use strict';

  const root = document.documentElement;
  const themeToggle = document.querySelector('[data-theme-toggle]');
  const mobileMenuBtn = document.querySelector('.mobile-menu-btn');
  const mobileNav = document.getElementById('mobile-nav');
  const header = document.getElementById('header');
  const fadeElements = document.querySelectorAll('.fade-in');
  const langButtons = document.querySelectorAll('[data-lang-switch]');

  const translations = {
    he: {
      /* ===== META ===== */
      pageTitle: 'מכון ילדי הקסם | בהנהלת ד״ר נמוז בסים',
      pageDescription: 'מכון ילדי הקסם בהנהלת ד״ר נמוז בסים. ליווי רפואי מקיף, מענה אישי לילדים ולהורים, ואבחון הפרעות קשב וריכוז בגישה מקצועית ורגישה.',
      dir: 'rtl',

      /* ===== SHARED ===== */
      skip: 'דלג לתוכן הראשי',
      'header.logo_name': 'מכון ילדי הקסם',
      'header.logo_sub': 'בהנהלת ד״ר נמוז בסים',
      'header.dr_name': 'ד״ר בסים נמוז',
      'header.dr_sub': 'רופא ילדים מומחה',

      /* ===== NAV ===== */
      'nav.home': 'דף הבית',
      'nav.about': 'אודות',
      'nav.treatments': 'תחומי טיפול',
      'nav.vision': 'למה אלינו',
      'nav.services': 'תחומי טיפול',
      'nav.director': 'היכרות',
      'nav.adhd': 'קשב וריכוז',
      'nav.portal': 'אזור מטופלים',
      'nav.contact': 'יצירת קשר',
      'nav.about_dr': 'אודות ד״ר בסים',
      'nav.adhd_full': 'הפרעות קשב וריכוז',
      'nav.booking': 'קביעת תור',

      /* ===== FOOTER (common) ===== */
      'footer.logo_name': 'מכון ילדי הקסם',
      'footer.logo_sub': 'בהנהלת ד״ר נמוז בסים',
      'footer.dr_name': 'ד״ר בסים נמוז',
      'footer.dr_sub': 'רופא ילדים מומחה',
      'footer.desc': 'מקום שמחבר בין ליווי רפואי מקצועי, גישה אנושית וכניסה דיגיטלית נוחה להורים ולמטופלים.',
      'footer.nav_title': 'ניווט מהיר',
      'footer.contact_title': 'יצירת קשר',
      'footer.whatsapp': 'וואטסאפ למזכירה',
      'footer.portal': 'כניסה לאזור המטופלים',
      'footer.copy': '© 2026 מכון ילדי הקסם. כל הזכויות שמורות.',
      'footer.copy_dr': '© 2026 ד״ר בסים נמוז. כל הזכויות שמורות.',
      'footer.nav_home': 'דף הבית',
      'footer.nav_about': 'אודות',
      'footer.nav_adhd': 'קשב וריכוז',
      'footer.nav_portal': 'אזור מטופלים',
      'footer.nav_treatments': 'תחומי טיפול',
      'footer.nav_contact': 'יצירת קשר',
      'footer.contact_section': 'צרו קשר',

      /* ===== INDEX PAGE ===== */
      'hero.badge': 'מכון ילדי הקסם',
      'hero.title': 'מכון ילדי הקסם <span>בהנהלת ד״ר נמוז בסים</span>',
      'hero.subtitle': 'מרחב מקצועי, רגיש ומכבד לילדים, להורים ולמשפחה כולה, עם מענה רפואי מקיף, ליווי אישי ואפשרות כניסה נוחה לאזור המטופלים.',
      'hero.booking': 'קביעת תור',
      'hero.portal': 'אזור מטופלים',
      'hero.director': 'הכירו את ד״ר בסים',
      'trust.one_number': 'ליווי',
      'trust.one_label': 'אישי לכל משפחה',
      'trust.two_number': 'מענה',
      'trust.two_label': 'לקשב וריכוז',
      'trust.three_number': 'גישה',
      'trust.three_label': 'רגישה ומקצועית',
      'trust.four_number': 'כניסה',
      'trust.four_label': 'נוחה לאזור מטופלים',
      'vision.eyebrow': 'החזון שלנו',
      'vision.title': 'מקום שמחבר בין מקצועיות, הקשבה וביטחון',
      'vision.desc': 'מכון ילדי הקסם נבנה כדי להעניק לילדים ולהורים תחושת רוגע, הכוונה מדויקת ודרך ברורה לקבלת טיפול, אבחון וליווי לאורך זמן.',
      'vision.card1_title': 'יחס חם ומכבד',
      'vision.card1_text': 'כל ילד וכל הורה מקבלים הקשבה אמיתית, ליווי רגוע והסברים ברורים בגובה העיניים.',
      'vision.card2_title': 'מענה מקצועי ומדויק',
      'vision.card2_text': 'אבחון, טיפול וליווי רפואי מתוך אחריות מקצועית, ניסיון וראייה רחבה של צרכי הילד והמשפחה.',
      'vision.card3_title': 'גישה מהירה ונוחה',
      'vision.card3_text': 'קביעת תור, יצירת קשר וכניסה לאזור המטופלים בצורה פשוטה, נגישה וברורה מכל מכשיר.',
      'services.eyebrow': 'מה תמצאו אצלנו',
      'services.title': 'תחומי הטיפול המרכזיים',
      'services.desc': 'המכון משלב ליווי רפואי, הערכה מקצועית, קשר רציף עם ההורים וגישה מותאמת לילדים ולבני נוער.',
      'services.item1': 'רפואת ילדים כללית',
      'services.item2': 'אבחון קשב וריכוז',
      'services.item3': 'ליווי הורים ומשפחה',
      'services.item4': 'בדיקות מעקב והתפתחות',
      'services.item5': 'הכוונה רפואית אישית',
      'services.item6': 'כניסה דיגיטלית לאזור מטופלים',
      'services.card1_text': 'מענה רפואי ראשוני, בדיקות שגרה והכוונה מקצועית לילדים בכל שלב.',
      'services.card2_text': 'אבחון מקיף עם הסתכלות רגישה ומדויקת על התפקוד של הילד בבית ובמסגרות.',
      'services.card3_text': 'שיח ברור, ליווי רגוע וכלים מעשיים שמחזקים את המשפחה כולה.',
      'services.card4_text': 'מעקב מסודר אחר גדילה, התפתחות וצרכים רפואיים לאורך זמן.',
      'services.card5_text': 'תוכנית ברורה ומותאמת אישית להמשך הדרך, עם מענה מדויק לשאלות ההורים.',
      'services.card6_text': 'כניסה פשוטה, נוחה וברורה למערכת המטופלים מכל מכשיר ובכל זמן.',
      'director.quote_title': 'הגישה שלנו',
      'director.quote_text': 'רפואה טובה לילדים מתחילה בהקשבה, בביטחון ובתחושה שיש מי שמלווה אתכם באמת לאורך הדרך.',
      'director.quote_signature': 'מכון ילדי הקסם בהנהלת ד״ר נמוז בסים',
      'director.eyebrow': 'בהנהלת ד״ר נמוז בסים',
      'director.title': 'הובלה רפואית עם לב אנושי',
      'director.text1': 'ד״ר נמוז בסים מוביל את המכון מתוך תפיסה שמחברת בין מקצועיות רפואית, יחס אישי, ותהליך ברור ומכבד עבור כל ילד והורה.',
      'director.text2': 'המכון נועד להיות מקום בטוח, אסתטי ונגיש, שבו אפשר לקבל ליווי רפואי, מענה בתחום קשב וריכוז, ותמיכה רציפה למשפחה כולה.',
      'director.tag1': 'רופא ילדים מומחה',
      'director.tag2': 'הכוונה אישית',
      'director.tag3': 'מענה למשפחה',
      'director.tag4': 'ליווי בקשב וריכוז',
      'contact.title': 'רוצים ליצור קשר עם המרפאה?',
      'contact.desc': 'אפשר לקבוע תור, לשלוח הודעת וואטסאפ למזכירת המרפאה, להיכנס לאזור המטופלים, או ליצור קשר טלפוני לכל שאלה.',
      'contact.whatsapp': 'קביעת תור בוואטסאפ',
      'contact.portal': 'אזור מטופלים',
      'contact.phone_label': 'טלפון:',
      'contact.mail_label': 'מייל:',
      'contact.address_label': 'כתובת:',
      'contact.address_value': 'רחוב תופיק זיאד 21, שפרעם',
      'contact.hours_label': 'תיאום:',
      'contact.hours_value': 'בתיאום מראש דרך המזכירה',

      /* ===== ABOUT PAGE ===== */
      'about.page_title': 'אודות ד״ר בסים נמוז | רופא ילדים מומחה',
      'about.page_desc': 'אודות ד״ר בסים נמוז, רופא ילדים מומחה עם גישה אישית, מקצועית ורגישה לילדים ולהורים.',
      'about.hero_badge': 'אודות',
      'about.hero_h1': 'אודות <span>ד״ר בסים נמוז</span>',
      'about.hero_subtitle': 'רופא ילדים מומחה, המעניק ליווי רפואי מקצועי, אישי ורגיש לילדים ולהורים, מתוך תפיסה רחבה של בריאות הילד והמשפחה.',
      'about.s1_eyebrow': 'הסיפור המקצועי',
      'about.s1_title': 'רפואה שמתחילה בהקשבה',
      'about.s1_p1': 'אני ד״ר בסים נמוז, רופא ילדים מומחה, ומאמין שרפואה טובה מתחילה קודם כול בהקשבה, באחריות ובקשר אישי עם הילד והמשפחה.',
      'about.s1_p2': 'לאורך השנים ליוויתי ילדים והורים במגוון רחב של מצבים רפואיים, מתוך מטרה אחת ברורה: להעניק טיפול מקצועי, מדויק ואנושי, כזה שלא מתמקד רק בסימפטום, אלא רואה את הילד כולו.',
      'about.s1_p3': 'מבחינתי, כל פגישה רפואית היא הזדמנות לעצור, להבין, לשאול את השאלות הנכונות, ולהתאים מענה נכון לצרכים של הילד ושל המשפחה. אני מאמין בשיח ברור, בגובה העיניים, ובהסבר שמאפשר להורים להרגיש בטוחים, רגועים ושותפים מלאים בתהליך.',
      'about.s2_eyebrow': 'הגישה שלי',
      'about.s2_title': 'מקצועיות, רגישות וליווי אישי',
      'about.card1_title': 'הקשבה אמיתית',
      'about.card1_text': 'להבין מה עובר על הילד, מה מטריד את ההורים, ומה באמת צריך לקרות כדי לעזור.',
      'about.card2_title': 'בדיקה יסודית',
      'about.card2_text': 'לבחון את התמונה המלאה, לחשוב בצורה רחבה, ולפעול מתוך אחריות מקצועית.',
      'about.card3_title': 'הסבר בגובה העיניים',
      'about.card3_text': 'לתת להורים תחושת ביטחון, סדר והבנה, כדי שיוכלו לקבל החלטות מתוך שקט.',
      'about.s3_eyebrow': 'תחומי עיסוק',
      'about.s3_title': 'מענה רפואי רחב',
      'about.t1': 'רפואת ילדים כללית',
      'about.t2': 'ייעוץ והכוונה להורים',
      'about.t3': 'הערכה ומעקב רפואי',
      'about.t4': 'אבחון וליווי בהפרעות קשב וריכוז',
      'about.cta_title': 'רוצים לקבוע תור או לשאול שאלה?',
      'about.cta_desc': 'אפשר ליצור קשר עם מזכירת המרפאה בוואטסאפ, בטלפון או במייל, ונשמח לעזור.',
      'about.cta_whatsapp': 'קביעת תור בוואטסאפ',
      'about.cta_contact': 'לפרטי קשר מלאים',

      /* ===== CONTACT PAGE ===== */
      'contact_page.page_title': 'יצירת קשר | ד״ר בסים נמוז',
      'contact_page.page_desc': 'יצירת קשר עם ד״ר בסים נמוז, פרטי המרפאה, שעות קבלת קהל ותיאום תור דרך מזכירת המרפאה.',
      'contact_page.hero_badge': 'יצירת קשר',
      'contact_page.hero_h1': 'אפשר לפנות אלינו <span>בקלות ובנוחות</span>',
      'contact_page.hero_subtitle': 'לקביעת תור, לשאלה רפואית כללית או לבירור ראשוני, אפשר ליצור קשר עם מזכירת המרפאה דרך וואטסאפ, בטלפון או במייל.',
      'contact_page.btn_whatsapp': 'פנייה בוואטסאפ',
      'contact_page.btn_call': 'התקשרו עכשיו',
      'contact_page.s1_eyebrow': 'פרטי המרפאה',
      'contact_page.s1_title': 'כל המידע במקום אחד',
      'contact_page.card1_title': 'וואטסאפ למזכירה',
      'contact_page.card1_text': 'לצורך קבלת תור יש ליצור קשר בהודעת וואטסאפ עם מזכירת המרפאה.',
      'contact_page.card2_title': 'טלפון',
      'contact_page.card2_text': 'אפשר ליצור קשר גם בטלפון בשעות הפעילות.',
      'contact_page.card3_title': 'דוא״ל',
      'contact_page.card3_text': 'לשאלות, פניות ועדכונים.',
      'contact_page.loc_eyebrow': 'מיקום',
      'contact_page.loc_title': 'כתובת המרפאה',
      'contact_page.loc_address': 'רחוב תופיק זיאד 21, שפרעם',
      'contact_page.info_address_label': 'כתובת:',
      'contact_page.info_address_value': 'רחוב תופיק זיאד 21, שפרעם',
      'contact_page.info_appt_label': 'תיאום תור:',
      'contact_page.info_appt_value': 'דרך מזכירת המרפאה בוואטסאפ או דרך אתר מכבי',
      'contact_page.info_email_label': 'דוא״ל:',
      'contact_page.hours_title': 'שעות קבלת קהל',
      'contact_page.day1': 'יום א׳',
      'contact_page.day1_hours': 'אין קבלת קהל',
      'contact_page.day2': 'יום ב׳',
      'contact_page.day2_hours': '09:00–16:00',
      'contact_page.day3': 'יום ג׳',
      'contact_page.day3_hours': '16:00–20:00',
      'contact_page.day4': 'יום ד׳',
      'contact_page.day4_hours': '16:00–20:00',
      'contact_page.day5': 'יום ה׳',
      'contact_page.day5_hours': '17:00–20:00',
      'contact_page.day6': 'יום ו׳',
      'contact_page.day6_hours': '09:30–12:30',
      'contact_page.day7': 'יום ש׳',
      'contact_page.day7_hours': '09:30–12:30',
      'contact_page.cta_title': 'רוצים שנחזור אליכם?',
      'contact_page.cta_desc': 'הדרך המהירה ביותר היא לשלוח הודעת וואטסאפ למזכירת המרפאה. אפשר גם ליצור קשר דרך אתר מכבי.',
      'contact_page.cta_whatsapp': 'שליחת הודעה בוואטסאפ',
      'contact_page.cta_email': 'שליחת מייל',

      /* ===== BOOKING PAGE ===== */
      'booking.page_title': 'קביעת תור | ד״ר בסים נמוז',
      'booking.page_desc': 'קביעת תור אצל ד״ר בסים נמוז דרך מזכירת המרפאה בוואטסאפ או דרך אתר מכבי.',
      'booking.hero_badge': 'קביעת תור',
      'booking.hero_h1': 'קביעת תור <span>בדרך פשוטה וברורה</span>',
      'booking.hero_subtitle': 'לצורך קבלת תור יש ליצור קשר בהודעת וואטסאפ עם מזכירת המרפאה. אפשר גם לפנות דרך אתר מכבי או ליצור קשר טלפוני.',
      'booking.btn_whatsapp': 'קביעת תור בוואטסאפ',
      'booking.btn_call': 'התקשרו למרפאה',
      'booking.s1_eyebrow': 'איך קובעים תור',
      'booking.s1_title': 'שלושה צעדים פשוטים',
      'booking.card1_title': 'פונים למזכירה',
      'booking.card1_text': 'שולחים הודעת וואטסאפ למזכירת המרפאה עם שם הילד וסיבת הפנייה.',
      'booking.card2_title': 'מקבלים הכוונה',
      'booking.card2_text': 'המזכירה מסייעת בבחירת מסלול מתאים ובהשלמת פרטים לתיאום.',
      'booking.card3_title': 'מתאמים מועד',
      'booking.card3_text': 'הפגישה נקבעת לפי זמני הקבלה של המרפאה ובתיאום מראש.',
      'booking.s2_eyebrow': 'אפשרויות תיאום',
      'booking.s2_title': 'איך הכי נוח לכם לפנות',
      'booking.info_wa_label': 'וואטסאפ למזכירה:',
      'booking.info_phone_label': 'טלפון:',
      'booking.info_email_label': 'מייל:',
      'booking.info_maccabi_label': 'דרך מכבי:',
      'booking.info_maccabi_value': 'ניתן לפנות גם דרך אתר מכבי.',
      'booking.hours_title': 'שעות קבלת קהל',
      'booking.day1': 'יום א׳',
      'booking.day1_hours': 'אין קבלת קהל',
      'booking.day2': 'יום ב׳',
      'booking.day2_hours': '09:00–16:00',
      'booking.day3': 'יום ג׳',
      'booking.day3_hours': '16:00–20:00',
      'booking.day4': 'יום ד׳',
      'booking.day4_hours': '16:00–20:00',
      'booking.day5': 'יום ה׳',
      'booking.day5_hours': '17:00–20:00',
      'booking.day6': 'יום ו׳',
      'booking.day6_hours': '09:30–12:30',
      'booking.day7': 'יום ש׳',
      'booking.day7_hours': '09:30–12:30',
      'booking.cta_title': 'מוכנים לקבוע?',
      'booking.cta_desc': 'הדרך המהירה ביותר היא לשלוח הודעת וואטסאפ למזכירת המרפאה.',
      'booking.cta_whatsapp': 'קביעת תור בוואטסאפ',
      'booking.cta_contact': 'ליצירת קשר',

      /* ===== CLINICFLOW PAGE ===== */
      'clinicflow.page_title': 'אזור מטופלים | כניסה למערכת',
      'clinicflow.page_desc': 'גישה לאזור המטופלים ולמערכת ClinicFlow לניהול תורים, כניסת צוות וכניסת מטופלים דרך ממשק אחד.',
      'clinicflow.hero_badge': 'אזור מטופלים',
      'clinicflow.hero_h1': 'כניסה מהירה <span>לאזור המטופלים</span>',
      'clinicflow.hero_subtitle': 'מערכת ClinicFlow מאפשרת כניסת צוות וכניסת מטופלים למערכת אחת, לצורך ניהול תורים, צפייה בפרטי ביקור, וביצוע פעולות בצורה פשוטה ונוחה.',
      'clinicflow.btn_enter': 'כניסה למערכת',
      'clinicflow.btn_booking': 'לקביעת תור',
      'clinicflow.s1_eyebrow': 'מה אפשר לעשות במערכת',
      'clinicflow.s1_title': 'מערכת אחת לשני סוגי משתמשים',
      'clinicflow.card1_title': 'כניסת צוות',
      'clinicflow.card1_text': 'גישה לניהול תורים, צפייה במטופלים, עדכון סטטוסים וניהול המשימות השוטפות.',
      'clinicflow.card2_title': 'כניסת מטופלים',
      'clinicflow.card2_text': 'כניסה עצמאית לצפייה בתורים, בקשת קוד ב־WhatsApp ואימות מהיר דרך הטלפון.',
      'clinicflow.card3_title': 'אימות ב־WhatsApp',
      'clinicflow.card3_text': 'מערכת המטופלים פועלת עם קוד חד־פעמי ב־WhatsApp, כך שהכניסה פשוטה ונגישה.',
      'clinicflow.s2_eyebrow': 'בדקנו בפועל',
      'clinicflow.s2_title': 'מה כבר נבדק במערכת',
      'clinicflow.check1_label': 'כניסת צוות:',
      'clinicflow.check1_value': 'נבדקה ועובדת',
      'clinicflow.check2_label': 'כניסת מטופל:',
      'clinicflow.check2_value': 'נבדקה ועובדת',
      'clinicflow.check3_label': 'שליחת קוד:',
      'clinicflow.check3_value': 'פועלת דרך WhatsApp',
      'clinicflow.check4_label': 'ממשק:',
      'clinicflow.check4_value': 'כולל מסלול צוות ומסלול מטופל',
      'clinicflow.steps_title': 'איך משתמשים',
      'clinicflow.step1_label': 'שלב 1',
      'clinicflow.step1_value': 'נכנסים למערכת',
      'clinicflow.step2_label': 'שלב 2',
      'clinicflow.step2_value': 'בוחרים צוות או מטופל',
      'clinicflow.step3_label': 'שלב 3',
      'clinicflow.step3_value': 'מקבלים קוד אימות',
      'clinicflow.step4_label': 'שלב 4',
      'clinicflow.step4_value': 'נכנסים ומבצעים את הפעולה הרצויה',
      'clinicflow.cta_title': 'רוצים להיכנס עכשיו לאזור המטופלים?',
      'clinicflow.cta_desc': 'אפשר לעבור למערכת ישירות מכאן, או ליצור קשר אם אתם צריכים עזרה בהתחברות.',
      'clinicflow.cta_enter': 'כניסה למערכת',
      'clinicflow.cta_help': 'צריכים עזרה?',

      /* ===== TREATMENTS PAGE ===== */
      'treatments.page_title': 'תחומי טיפול | ד״ר בסים נמוז',
      'treatments.page_desc': 'תחומי הטיפול של ד״ר בסים נמוז: רפואת ילדים, ייעוץ להורים, מעקב רפואי והפרעות קשב וריכוז.',
      'treatments.hero_badge': 'תחומי טיפול',
      'treatments.hero_h1': 'מענה רפואי רחב <span>לילדים ולהורים</span>',
      'treatments.hero_subtitle': 'האתר מרכז מגוון שירותים רפואיים ותחומי ליווי עבור ילדים והורים, מתוך מטרה להעניק טיפול איכותי, ברור ומותאם אישית.',
      'treatments.btn_booking': 'לקביעת תור',
      'treatments.btn_contact': 'ליצירת קשר',
      'treatments.s1_eyebrow': 'מעטפת מקצועית',
      'treatments.s1_title': 'השירותים המרכזיים במרפאה',
      'treatments.card1_title': 'רפואת ילדים כללית',
      'treatments.card1_text': 'בדיקות, הערכות, ליווי רפואי ומענה מקצועי למגוון מצבים שכיחים בילדות.',
      'treatments.card2_title': 'ייעוץ להורים',
      'treatments.card2_text': 'הכוונה מקצועית בשפה ברורה ונגישה, כדי לעזור להורים להבין את המצב ולקבל החלטות בביטחון.',
      'treatments.card3_title': 'מעקב רפואי',
      'treatments.card3_text': 'ליווי לאורך זמן במצבים שבהם נדרש מעקב, בקרה, חזרה לבדיקות והתאמת המשך הדרך.',
      'treatments.card4_title': 'הפרעות קשב וריכוז',
      'treatments.card4_text': 'בירור, הערכה וליווי בתחום הפרעות קשב וריכוז, מתוך הסתכלות רחבה על הילד, המשפחה והתפקוד.',
      'treatments.s2_eyebrow': 'תחומי עיסוק',
      'treatments.s2_title': 'במה ניתן לפנות אלינו',
      'treatments.t1': 'רפואת ילדים כללית',
      'treatments.t2': 'חיסונים וייעוץ מונע',
      'treatments.t3': 'בדיקות שגרה ומעקב גדילה',
      'treatments.t4': 'ייעוץ להורים',
      'treatments.t5': 'הערכה ומעקב רפואי',
      'treatments.t6': 'בעיות נשימה ואלרגיות',
      'treatments.t7': 'זיהומים ומחלות ילדים',
      'treatments.t8': 'הפרעות קשב וריכוז',
      'treatments.s3_eyebrow': 'איך אנחנו עובדים',
      'treatments.s3_title': 'מענה רפואי בגישה אישית',
      'treatments.s3_desc': 'הטיפול אינו מסתיים רק בבדיקה. המטרה היא להבין את צורכי הילד, להסביר להורים את התמונה, ולבנות דרך ברורה להמשך.',
      'treatments.approach1_label': 'גישה אישית:',
      'treatments.approach1_value': 'כל ילד וכל משפחה מקבלים יחס מותאם ואנושי.',
      'treatments.approach2_label': 'הקשבה להורים:',
      'treatments.approach2_value': 'מקום לשאלות, להסברים ולשותפות מלאה בתהליך.',
      'treatments.approach3_label': 'מענה מקצועי:',
      'treatments.approach3_value': 'בדיקה יסודית, חשיבה רחבה וליווי לפי הצורך.',
      'treatments.cta_title': 'צריכים עזרה בבחירת תחום הטיפול המתאים?',
      'treatments.cta_desc': 'אפשר לפנות אלינו ונכוון אתכם למסלול המתאים ביותר עבור הילד והמשפחה.',
      'treatments.cta_contact': 'יצירת קשר',
      'treatments.cta_booking': 'לקביעת תור',

      /* ===== ADHD PAGE ===== */
      'adhd.page_title': 'הפרעות קשב וריכוז | ד״ר בסים נמוז',
      'adhd.page_desc': 'אבחון, ליווי והכוונה מקצועית לילדים ולהורים בתחום הפרעות קשב וריכוז.',
      'adhd.hero_badge': 'התמחות מיוחדת',
      'adhd.hero_h1': 'הפרעות קשב וריכוז <span>אבחון, ליווי והכוונה מקצועית</span>',
      'adhd.hero_subtitle': 'מענה מקצועי, רגיש ומדויק להורים ולילדים המתמודדים עם שאלות, קשיים או חשד להפרעת קשב וריכוז.',
      'adhd.btn_assess': 'לקביעת הערכה ראשונית',
      'adhd.btn_signs': 'מה הסימנים',
      'adhd.s1_eyebrow': 'מבט רחב',
      'adhd.s1_title': 'להבין את הילד, לא רק את הכותרת',
      'adhd.s1_p1': 'הפרעות קשב וריכוז יכולות להשפיע על תחומים רבים בחיי הילד. לעיתים הקושי מופיע במסגרת הלימודים, לעיתים בבית, ולעיתים בקשרים החברתיים, בהתארגנות, בהתמדה, בריכוז או בתחושת המסוגלות.',
      'adhd.s1_p2': 'כאשר עולות שאלות או התלבטויות, חשוב לפנות לבירור מקצועי, מסודר ואחראי. המטרה היא לא למהר להדביק כותרת, אלא להבין את הילד לעומק, לבחון את התמונה כולה, ולבנות דרך מתאימה ונכונה להמשך.',
      'adhd.signs_eyebrow': 'מתי כדאי לפנות',
      'adhd.signs_title': 'סימנים שכדאי לשים לב אליהם',
      'adhd.sign1_title': 'קושי מתמשך בריכוז',
      'adhd.sign1_text': 'קושי לשבת לאורך זמן, לעקוב אחרי הוראות או להשלים משימות.',
      'adhd.sign2_title': 'מוסחות גבוהה',
      'adhd.sign2_text': 'מעבר מהיר בין גירויים, קושי לשמור על רצף ותחושת פיזור כללית.',
      'adhd.sign3_title': 'חוסר שקט או אימפולסיביות',
      'adhd.sign3_text': 'תנועתיות מוגברת, תגובות מהירות, קושי להמתין או לעצור.',
      'adhd.sign4_title': 'קושי בהתארגנות',
      'adhd.sign4_text': 'שכחנות, איבוד חפצים, קושי בניהול זמן או בסדר יום.',
      'adhd.sign5_title': 'פער בין יכולת לתפקוד',
      'adhd.sign5_text': 'הילד חכם ומסוגל, אך מתקשה לממש את יכולותיו בפועל.',
      'adhd.sign6_title': 'פניות מהמסגרת החינוכית',
      'adhd.sign6_text': 'הערות מצד בית הספר או הגן על קשיי קשב, התארגנות או התנהגות.',
      'adhd.process_eyebrow': 'איך נראה התהליך',
      'adhd.process_title': 'בירור, הערכה והכוונה להמשך',
      'adhd.process_text': 'הגישה שלי בתחום זה מבוססת על בדיקה רחבה ומסודרת, הכוללת היכרות עם הילד והמשפחה, הקשבה לקשיים, לשאלות ולמטרות, הבנת התפקוד של הילד בבית ובמסגרת החינוכית, הערכה מקצועית ואחראית, והכוונה להמשך הדרך בהתאם לצורך.',
      'adhd.feat1_title': 'אבחון מקצועי ומעמיק',
      'adhd.feat1_text': 'בחינה מסודרת של התמונה המלאה לפני קבלת החלטות.',
      'adhd.feat2_title': 'ליווי משפחתי',
      'adhd.feat2_text': 'מתן הסבר, סדר והכוונה גם להורים, לא רק לילד.',
      'adhd.feat3_title': 'תכנון מותאם אישית',
      'adhd.feat3_text': 'התאמת הדרך הנכונה ביותר לילד לפי צרכיו, סביבתו ותפקודו.',
      'adhd.who_title': 'למי מתאים לפנות',
      'adhd.who1': 'הורים שמתלבטים אם יש צורך בבירור',
      'adhd.who2': 'משפחות שקיבלו הערות מהמסגרת החינוכית',
      'adhd.who3': 'ילדים שמתקשים להתרכז או להתארגן',
      'adhd.who4': 'הורים שרוצים להבין טוב יותר מה עובר על הילד',
      'adhd.cta_title': 'יש שאלות או צורך בהערכה?',
      'adhd.cta_desc': 'אפשר לפנות למזכירת המרפאה בוואטסאפ ולקבל הכוונה מסודרת להמשך.',
      'adhd.cta_whatsapp': 'פנייה בוואטסאפ',
      'adhd.cta_contact': 'לפרטי קשר מלאים',

      /* ===== DOCTORS PAGE ===== */
      'doctors.page_title': 'רופאים נוספים | ד״ר בסים נמוז',
      'doctors.page_desc': 'רופאים ואנשי מקצוע נוספים שיכולים להצטרף בעתיד לאתר כמרחב מקצועי רחב יותר.',
      'doctors.hero_badge': 'התרחבות עתידית',
      'doctors.hero_h1': 'רופאים נוספים <span>ומרחב מקצועי רחב יותר</span>',
      'doctors.hero_subtitle': 'האתר נבנה מתוך חזון רחב יותר, כך שיוכל לכלול בהמשך גם רופאים ואנשי מקצוע נוספים, כדי לתת למשפחות מענה רחב, איכותי ומסודר במקום אחד.',
      'doctors.btn_contact': 'ליצירת קשר',
      'doctors.btn_home': 'חזרה לדף הבית',
      'doctors.s1_eyebrow': 'החזון',
      'doctors.s1_title': 'מקום מקצועי שיכול לגדול יחד איתכם',
      'doctors.s1_desc': 'המטרה היא ליצור מקום מקצועי, אמין ומסודר שבו משפחות יוכלו למצוא מידע, הכוונה ואנשי מקצוע איכותיים, תוך שמירה על רמה מקצועית גבוהה ותחושת אמון.',
      'doctors.card1_title': 'תחומי מומחיות נוספים',
      'doctors.card1_text': 'רופאים ואנשי מקצוע משלימים שיכולים להרחיב את המענה הניתן למשפחות.',
      'doctors.card2_title': 'שיתופי פעולה איכותיים',
      'doctors.card2_text': 'עבודה משותפת עם אנשי מקצוע שאתה מכיר וסומך עליהם.',
      'doctors.card3_title': 'מעטפת רחבה למשפחה',
      'doctors.card3_text': 'מקום אחד שמחבר בין טיפול, מידע, הכוונה והפניה לאנשי מקצוע נוספים.',
      'doctors.future_eyebrow': 'בקרוב',
      'doctors.future_title': 'כאן יופיעו בעתיד כרטיסי רופאים',
      'doctors.future_desc': 'לכל רופא יהיה אזור ייעודי עם שם, תחום התמחות, תיאור קצר ופרטי יצירת קשר או מעבר לפרופיל מלא.',
      'doctors.coming_soon': 'רופאים נוספים ותחומים חדשים — בקרוב',
      'doctors.cta_title': 'רוצים לשלב בעתיד רופאים נוספים באתר?',
      'doctors.cta_desc': 'אפשר ליצור קשר ולהתחיל לתכנן את ההרחבה של האתר למרחב מקצועי רחב יותר.',
      'doctors.cta_contact': 'ליצירת קשר',
      'doctors.cta_home': 'חזרה לדף הבית'
    },

    ar: {
      /* ===== META ===== */
      pageTitle: 'معهد أطفال السحر | بإدارة الدكتور باسم نموز',
      pageDescription: 'معهد أطفال السحر بإدارة الدكتور باسم نموز. مرافقة طبية شاملة للأطفال والأهالي، وتشخيص اضطرابات الانتباه والتركيز بأسلوب مهني وإنساني.',
      dir: 'rtl',

      /* ===== SHARED ===== */
      skip: 'تخطي إلى المحتوى الرئيسي',
      'header.logo_name': 'معهد أطفال السحر',
      'header.logo_sub': 'بإدارة الدكتور باسم نموز',
      'header.dr_name': 'د. بسيم نموز',
      'header.dr_sub': 'طبيب أطفال مختص',

      /* ===== NAV ===== */
      'nav.home': 'الرئيسية',
      'nav.about': 'عن العيادة',
      'nav.treatments': 'مجالات العلاج',
      'nav.vision': 'لماذا نحن',
      'nav.services': 'مجالات العلاج',
      'nav.director': 'تعرفوا علينا',
      'nav.adhd': 'الانتباه والتركيز',
      'nav.portal': 'منطقة المرضى',
      'nav.contact': 'تواصل',
      'nav.about_dr': 'عن د. بسيم نموز',
      'nav.adhd_full': 'اضطرابات الانتباه والتركيز',
      'nav.booking': 'حجز موعد',

      /* ===== FOOTER (common) ===== */
      'footer.logo_name': 'معهد أطفال السحر',
      'footer.logo_sub': 'بإدارة الدكتور باسم نموز',
      'footer.dr_name': 'د. بسيم نموز',
      'footer.dr_sub': 'طبيب أطفال مختص',
      'footer.desc': 'مكان يجمع بين المرافقة الطبية المهنية، النهج الإنساني، والدخول الرقمي المريح للأهالي والمرضى.',
      'footer.nav_title': 'تنقل سريع',
      'footer.contact_title': 'تواصل',
      'footer.whatsapp': 'واتساب للسكرتيرة',
      'footer.portal': 'الدخول إلى منطقة المرضى',
      'footer.copy': '© 2026 معهد أطفال السحر. جميع الحقوق محفوظة.',
      'footer.copy_dr': '© 2026 د. بسيم نموز. جميع الحقوق محفوظة.',
      'footer.nav_home': 'الرئيسية',
      'footer.nav_about': 'عن العيادة',
      'footer.nav_adhd': 'الانتباه والتركيز',
      'footer.nav_portal': 'منطقة المرضى',
      'footer.nav_treatments': 'مجالات العلاج',
      'footer.nav_contact': 'تواصل',
      'footer.contact_section': 'تواصل معنا',

      /* ===== INDEX PAGE ===== */
      'hero.badge': 'معهد أطفال السحر',
      'hero.title': 'معهد أطفال السحر <span>بإدارة الدكتور باسم نموز</span>',
      'hero.subtitle': 'مساحة مهنية، حساسة ومحترمة للأطفال والأهالي، مع مرافقة طبية شاملة وإمكانية دخول مريحة إلى منطقة المرضى.',
      'hero.booking': 'حجز موعد',
      'hero.portal': 'منطقة المرضى',
      'hero.director': 'تعرفوا على الدكتور باسم',
      'trust.one_number': 'مرافقة',
      'trust.one_label': 'شخصية لكل عائلة',
      'trust.two_number': 'دعم',
      'trust.two_label': 'للانتباه والتركيز',
      'trust.three_number': 'نهج',
      'trust.three_label': 'مهني وإنساني',
      'trust.four_number': 'دخول',
      'trust.four_label': 'مريح لمنطقة المرضى',
      'vision.eyebrow': 'رؤيتنا',
      'vision.title': 'مكان يجمع بين المهنية، الإصغاء والطمأنينة',
      'vision.desc': 'أُنشئ معهد أطفال السحر ليمنح الأطفال والأهالي شعوراً بالهدوء، وتوجيهاً دقيقاً وطريقاً واضحاً للعلاج والتشخيص والمرافقة المستمرة.',
      'vision.card1_title': 'تعامل دافئ ومحترم',
      'vision.card1_text': 'كل طفل وكل ولي أمر يحصل على إصغاء حقيقي ومرافقة هادئة وشرح واضح وبسيط.',
      'vision.card2_title': 'استجابة مهنية دقيقة',
      'vision.card2_text': 'تشخيص وعلاج ومرافقة طبية بمسؤولية مهنية وخبرة ورؤية واسعة لاحتياجات الطفل والعائلة.',
      'vision.card3_title': 'وصول سريع ومريح',
      'vision.card3_text': 'حجز موعد، تواصل، ودخول إلى منطقة المرضى بشكل بسيط وواضح من أي جهاز.',
      'services.eyebrow': 'ماذا تجدون لدينا',
      'services.title': 'مجالات العلاج الأساسية',
      'services.desc': 'المعهد يجمع بين المرافقة الطبية، التقييم المهني، التواصل المستمر مع الأهل ونهج ملائم للأطفال واليافعين.',
      'services.item1': 'طب أطفال عام',
      'services.item2': 'تشخيص الانتباه والتركيز',
      'services.item3': 'مرافقة للأهل والعائلة',
      'services.item4': 'فحوصات متابعة وتطور',
      'services.item5': 'توجيه طبي شخصي',
      'services.item6': 'دخول رقمي لمنطقة المرضى',
      'services.card1_text': 'استجابة طبية أولية، فحوصات روتينية وتوجيه مهني للأطفال في كل مرحلة.',
      'services.card2_text': 'تشخيص شامل مع نظرة حساسة ودقيقة لأداء الطفل في البيت وفي الأطر المختلفة.',
      'services.card3_text': 'حوار واضح، مرافقة هادئة وأدوات عملية تدعم العائلة كلها.',
      'services.card4_text': 'متابعة منظمة للنمو والتطور والاحتياجات الطبية مع مرور الوقت.',
      'services.card5_text': 'خطة واضحة وشخصية للخطوات القادمة مع إجابات دقيقة لأسئلة الأهل.',
      'services.card6_text': 'دخول بسيط ومريح وواضح إلى نظام المرضى من أي جهاز وفي أي وقت.',
      'director.quote_title': 'نهجنا',
      'director.quote_text': 'الطب الجيد للأطفال يبدأ بالإصغاء، بالثقة، وبالشعور أن هناك من يرافقكم فعلاً طوال الطريق.',
      'director.quote_signature': 'معهد أطفال السحر بإدارة الدكتور باسم نموز',
      'director.eyebrow': 'بإدارة الدكتور باسم نموز',
      'director.title': 'قيادة طبية بقلب إنساني',
      'director.text1': 'يقود الدكتور باسم نموز المعهد من خلال رؤية تجمع بين المهنية الطبية، التعامل الشخصي، ومسار واضح ومحترم لكل طفل وولي أمر.',
      'director.text2': 'صُمم المعهد ليكون مكاناً آمناً، جميلاً ومتاحاً، يمكن من خلاله الحصول على مرافقة طبية، دعم في مجال الانتباه والتركيز، ومساندة متواصلة للعائلة كلها.',
      'director.tag1': 'طبيب أطفال مختص',
      'director.tag2': 'توجيه شخصي',
      'director.tag3': 'دعم للعائلة',
      'director.tag4': 'مرافقة في الانتباه والتركيز',
      'contact.title': 'هل ترغبون بالتواصل مع العيادة؟',
      'contact.desc': 'يمكنكم حجز موعد، إرسال رسالة واتساب لسكرتيرة العيادة، الدخول إلى منطقة المرضى، أو الاتصال هاتفياً لأي استفسار.',
      'contact.whatsapp': 'حجز موعد عبر واتساب',
      'contact.portal': 'منطقة المرضى',
      'contact.phone_label': 'الهاتف:',
      'contact.mail_label': 'البريد:',
      'contact.address_label': 'العنوان:',
      'contact.address_value': 'شارع توفيق زياد 21، شفاعمرو',
      'contact.hours_label': 'التنسيق:',
      'contact.hours_value': 'بالتنسيق المسبق عبر السكرتيرة',

      /* ===== ABOUT PAGE ===== */
      'about.page_title': 'عن د. بسيم نموز | طبيب أطفال مختص',
      'about.page_desc': 'عن الدكتور باسم نموز، طبيب أطفال مختص بنهج شخصي ومهني وإنساني مع الأطفال والأهالي.',
      'about.hero_badge': 'عن الطبيب',
      'about.hero_h1': 'عن <span>د. بسيم نموز</span>',
      'about.hero_subtitle': 'طبيب أطفال مختص يقدم مرافقة طبية مهنية وشخصية وإنسانية للأطفال والأهالي، برؤية شاملة لصحة الطفل والعائلة.',
      'about.s1_eyebrow': 'القصة المهنية',
      'about.s1_title': 'طب يبدأ بالإصغاء',
      'about.s1_p1': 'أنا الدكتور باسم نموز، طبيب أطفال مختص، وأؤمن أن الطب الجيد يبدأ أولاً بالإصغاء، والمسؤولية، والتواصل الشخصي مع الطفل والعائلة.',
      'about.s1_p2': 'على مدار السنوات رافقت أطفالاً وأهالي في مجموعة واسعة من الحالات الطبية، من هدف واحد واضح: تقديم علاج مهني ودقيق وإنساني، لا يركز فقط على الأعراض بل يرى الطفل بأكمله.',
      'about.s1_p3': 'بالنسبة لي، كل لقاء طبي هو فرصة للتوقف، والفهم، وطرح الأسئلة الصحيحة، وتقديم الإجابة الملائمة لاحتياجات الطفل والعائلة. أؤمن بالحوار الواضح والشرح الذي يجعل الأهل يشعرون بالأمان والراحة وأنهم شركاء كاملون في العملية.',
      'about.s2_eyebrow': 'نهجي',
      'about.s2_title': 'المهنية والحساسية والمرافقة الشخصية',
      'about.card1_title': 'إصغاء حقيقي',
      'about.card1_text': 'فهم ما يمر به الطفل، ما يقلق الأهل، وما يجب أن يحدث فعلاً للمساعدة.',
      'about.card2_title': 'فحص معمّق',
      'about.card2_text': 'فحص الصورة الكاملة، والتفكير بشكل واسع، والتصرف بمسؤولية مهنية.',
      'about.card3_title': 'شرح بسيط وواضح',
      'about.card3_text': 'منح الأهل شعوراً بالأمان والنظام والفهم، لكي يتمكنوا من اتخاذ القرارات بهدوء.',
      'about.s3_eyebrow': 'مجالات العمل',
      'about.s3_title': 'استجابة طبية شاملة',
      'about.t1': 'طب أطفال عام',
      'about.t2': 'استشارات وإرشاد للأهل',
      'about.t3': 'تقييم ومتابعة طبية',
      'about.t4': 'تشخيص ومرافقة في اضطرابات الانتباه والتركيز',
      'about.cta_title': 'هل ترغبون بحجز موعد أو طرح سؤال؟',
      'about.cta_desc': 'يمكن التواصل مع سكرتيرة العيادة عبر واتساب أو الهاتف أو البريد الإلكتروني، ويسعدنا مساعدتكم.',
      'about.cta_whatsapp': 'حجز موعد عبر واتساب',
      'about.cta_contact': 'لتفاصيل التواصل الكاملة',

      /* ===== CONTACT PAGE ===== */
      'contact_page.page_title': 'تواصل | د. بسيم نموز',
      'contact_page.page_desc': 'التواصل مع الدكتور باسم نموز، تفاصيل العيادة، ساعات الاستقبال وتنسيق المواعيد عبر سكرتيرة العيادة.',
      'contact_page.hero_badge': 'تواصل معنا',
      'contact_page.hero_h1': 'يمكنكم التواصل معنا <span>بسهولة وراحة</span>',
      'contact_page.hero_subtitle': 'لحجز موعد، أو سؤال طبي عام، أو استفسار أولي، يمكن التواصل مع سكرتيرة العيادة عبر واتساب أو الهاتف أو البريد الإلكتروني.',
      'contact_page.btn_whatsapp': 'تواصل عبر واتساب',
      'contact_page.btn_call': 'اتصلوا الآن',
      'contact_page.s1_eyebrow': 'تفاصيل العيادة',
      'contact_page.s1_title': 'كل المعلومات في مكان واحد',
      'contact_page.card1_title': 'واتساب للسكرتيرة',
      'contact_page.card1_text': 'للحصول على موعد، يرجى التواصل برسالة واتساب مع سكرتيرة العيادة.',
      'contact_page.card2_title': 'الهاتف',
      'contact_page.card2_text': 'يمكن التواصل أيضاً عبر الهاتف خلال ساعات العمل.',
      'contact_page.card3_title': 'البريد الإلكتروني',
      'contact_page.card3_text': 'للأسئلة والاستفسارات والتحديثات.',
      'contact_page.loc_eyebrow': 'الموقع',
      'contact_page.loc_title': 'عنوان العيادة',
      'contact_page.loc_address': 'شارع توفيق زياد 21، شفاعمرو',
      'contact_page.info_address_label': 'العنوان:',
      'contact_page.info_address_value': 'شارع توفيق زياد 21، شفاعمرو',
      'contact_page.info_appt_label': 'تنسيق الموعد:',
      'contact_page.info_appt_value': 'عبر سكرتيرة العيادة بواتساب أو موقع ماكابي',
      'contact_page.info_email_label': 'البريد:',
      'contact_page.hours_title': 'ساعات الاستقبال',
      'contact_page.day1': 'الأحد',
      'contact_page.day1_hours': 'لا استقبال',
      'contact_page.day2': 'الاثنين',
      'contact_page.day2_hours': '09:00–16:00',
      'contact_page.day3': 'الثلاثاء',
      'contact_page.day3_hours': '16:00–20:00',
      'contact_page.day4': 'الأربعاء',
      'contact_page.day4_hours': '16:00–20:00',
      'contact_page.day5': 'الخميس',
      'contact_page.day5_hours': '17:00–20:00',
      'contact_page.day6': 'الجمعة',
      'contact_page.day6_hours': '09:30–12:30',
      'contact_page.day7': 'السبت',
      'contact_page.day7_hours': '09:30–12:30',
      'contact_page.cta_title': 'هل تريدون أن نتواصل معكم؟',
      'contact_page.cta_desc': 'أسرع طريقة هي إرسال رسالة واتساب لسكرتيرة العيادة. يمكن أيضاً التواصل عبر موقع ماكابي.',
      'contact_page.cta_whatsapp': 'إرسال رسالة واتساب',
      'contact_page.cta_email': 'إرسال بريد إلكتروني',

      /* ===== BOOKING PAGE ===== */
      'booking.page_title': 'حجز موعد | د. بسيم نموز',
      'booking.page_desc': 'حجز موعد عند الدكتور باسم نموز عبر سكرتيرة العيادة بواتساب أو موقع ماكابي.',
      'booking.hero_badge': 'حجز موعد',
      'booking.hero_h1': 'حجز موعد <span>بطريقة سهلة وواضحة</span>',
      'booking.hero_subtitle': 'للحصول على موعد، يرجى التواصل برسالة واتساب مع سكرتيرة العيادة. يمكن أيضاً التوجه عبر موقع ماكابي أو الاتصال الهاتفي.',
      'booking.btn_whatsapp': 'حجز موعد عبر واتساب',
      'booking.btn_call': 'اتصلوا بالعيادة',
      'booking.s1_eyebrow': 'كيفية حجز الموعد',
      'booking.s1_title': 'ثلاث خطوات بسيطة',
      'booking.card1_title': 'تواصلوا مع السكرتيرة',
      'booking.card1_text': 'أرسلوا رسالة واتساب لسكرتيرة العيادة مع اسم الطفل وسبب المراجعة.',
      'booking.card2_title': 'تلقوا التوجيه',
      'booking.card2_text': 'ستساعدكم السكرتيرة في اختيار المسار المناسب وإتمام تفاصيل التنسيق.',
      'booking.card3_title': 'تنسيق الموعد',
      'booking.card3_text': 'يُحدد الموعد وفق أوقات استقبال العيادة وبتنسيق مسبق.',
      'booking.s2_eyebrow': 'خيارات التنسيق',
      'booking.s2_title': 'ما هو الأنسب لكم',
      'booking.info_wa_label': 'واتساب للسكرتيرة:',
      'booking.info_phone_label': 'الهاتف:',
      'booking.info_email_label': 'البريد:',
      'booking.info_maccabi_label': 'عبر ماكابي:',
      'booking.info_maccabi_value': 'يمكن التوجه أيضاً عبر موقع ماكابي.',
      'booking.hours_title': 'ساعات الاستقبال',
      'booking.day1': 'الأحد',
      'booking.day1_hours': 'لا استقبال',
      'booking.day2': 'الاثنين',
      'booking.day2_hours': '09:00–16:00',
      'booking.day3': 'الثلاثاء',
      'booking.day3_hours': '16:00–20:00',
      'booking.day4': 'الأربعاء',
      'booking.day4_hours': '16:00–20:00',
      'booking.day5': 'الخميس',
      'booking.day5_hours': '17:00–20:00',
      'booking.day6': 'الجمعة',
      'booking.day6_hours': '09:30–12:30',
      'booking.day7': 'السبت',
      'booking.day7_hours': '09:30–12:30',
      'booking.cta_title': 'مستعدون للحجز؟',
      'booking.cta_desc': 'أسرع طريقة هي إرسال رسالة واتساب لسكرتيرة العيادة.',
      'booking.cta_whatsapp': 'حجز موعد عبر واتساب',
      'booking.cta_contact': 'للتواصل معنا',

      /* ===== CLINICFLOW PAGE ===== */
      'clinicflow.page_title': 'منطقة المرضى | دخول للنظام',
      'clinicflow.page_desc': 'الوصول إلى منطقة المرضى ونظام ClinicFlow لإدارة المواعيد، دخول الطاقم، ودخول المرضى من خلال واجهة واحدة.',
      'clinicflow.hero_badge': 'منطقة المرضى',
      'clinicflow.hero_h1': 'دخول سريع <span>لمنطقة المرضى</span>',
      'clinicflow.hero_subtitle': 'نظام ClinicFlow يتيح دخول الطاقم والمرضى إلى منظومة واحدة لإدارة المواعيد، الاطلاع على تفاصيل الزيارة، وتنفيذ الإجراءات بشكل بسيط ومريح.',
      'clinicflow.btn_enter': 'الدخول للنظام',
      'clinicflow.btn_booking': 'لحجز موعد',
      'clinicflow.s1_eyebrow': 'ما يمكن فعله في النظام',
      'clinicflow.s1_title': 'منظومة واحدة لنوعين من المستخدمين',
      'clinicflow.card1_title': 'دخول الطاقم',
      'clinicflow.card1_text': 'الوصول لإدارة المواعيد، الاطلاع على المرضى، تحديث الحالات وإدارة المهام اليومية.',
      'clinicflow.card2_title': 'دخول المرضى',
      'clinicflow.card2_text': 'دخول مستقل للاطلاع على المواعيد، طلب رمز عبر WhatsApp والتحقق السريع.',
      'clinicflow.card3_title': 'التحقق عبر WhatsApp',
      'clinicflow.card3_text': 'يعمل نظام المرضى برمز أحادي الاستخدام عبر WhatsApp، مما يجعل الدخول سهلاً وميسراً.',
      'clinicflow.s2_eyebrow': 'تم اختباره فعلياً',
      'clinicflow.s2_title': 'ما تم اختباره في النظام',
      'clinicflow.check1_label': 'دخول الطاقم:',
      'clinicflow.check1_value': 'تم اختباره ويعمل',
      'clinicflow.check2_label': 'دخول المريض:',
      'clinicflow.check2_value': 'تم اختباره ويعمل',
      'clinicflow.check3_label': 'إرسال الرمز:',
      'clinicflow.check3_value': 'يعمل عبر WhatsApp',
      'clinicflow.check4_label': 'الواجهة:',
      'clinicflow.check4_value': 'تشمل مسار الطاقم ومسار المريض',
      'clinicflow.steps_title': 'كيفية الاستخدام',
      'clinicflow.step1_label': 'الخطوة 1',
      'clinicflow.step1_value': 'الدخول للنظام',
      'clinicflow.step2_label': 'الخطوة 2',
      'clinicflow.step2_value': 'اختيار طاقم أو مريض',
      'clinicflow.step3_label': 'الخطوة 3',
      'clinicflow.step3_value': 'استلام رمز التحقق',
      'clinicflow.step4_label': 'الخطوة 4',
      'clinicflow.step4_value': 'الدخول وتنفيذ الإجراء المطلوب',
      'clinicflow.cta_title': 'هل تريدون الدخول الآن لمنطقة المرضى؟',
      'clinicflow.cta_desc': 'يمكنكم الانتقال للنظام مباشرة من هنا، أو التواصل معنا إذا كنتم بحاجة إلى مساعدة في تسجيل الدخول.',
      'clinicflow.cta_enter': 'الدخول للنظام',
      'clinicflow.cta_help': 'تحتاجون مساعدة؟',

      /* ===== TREATMENTS PAGE ===== */
      'treatments.page_title': 'مجالات العلاج | د. بسيم نموز',
      'treatments.page_desc': 'مجالات علاج الدكتور باسم نموز: طب الأطفال، إرشاد الأهل، المتابعة الطبية واضطرابات الانتباه والتركيز.',
      'treatments.hero_badge': 'مجالات العلاج',
      'treatments.hero_h1': 'استجابة طبية شاملة <span>للأطفال والأهالي</span>',
      'treatments.hero_subtitle': 'الموقع يجمع مجموعة متنوعة من الخدمات الطبية ومجالات المرافقة للأطفال والأهالي، بهدف تقديم علاج عالي الجودة وواضح ومخصص.',
      'treatments.btn_booking': 'لحجز موعد',
      'treatments.btn_contact': 'للتواصل معنا',
      'treatments.s1_eyebrow': 'مظلة مهنية',
      'treatments.s1_title': 'الخدمات الرئيسية في العيادة',
      'treatments.card1_title': 'طب أطفال عام',
      'treatments.card1_text': 'فحوصات وتقييمات ومرافقة طبية واستجابة مهنية لمجموعة واسعة من الحالات الشائعة في الطفولة.',
      'treatments.card2_title': 'إرشاد للأهل',
      'treatments.card2_text': 'توجيه مهني بلغة واضحة وسهلة المنال، لمساعدة الأهل على فهم الوضع واتخاذ القرارات بثقة.',
      'treatments.card3_title': 'متابعة طبية',
      'treatments.card3_text': 'مرافقة طويلة الأمد في الحالات التي تستوجب متابعة ومراقبة وعودة للفحص وتعديل مسار العلاج.',
      'treatments.card4_title': 'اضطرابات الانتباه والتركيز',
      'treatments.card4_text': 'استقصاء وتقييم ومرافقة في مجال اضطرابات الانتباه والتركيز، برؤية شاملة للطفل والعائلة والأداء.',
      'treatments.s2_eyebrow': 'مجالات العمل',
      'treatments.s2_title': 'بما يمكنكم مراجعتنا',
      'treatments.t1': 'طب أطفال عام',
      'treatments.t2': 'التطعيمات والإرشاد الوقائي',
      'treatments.t3': 'فحوصات الروتين ومتابعة النمو',
      'treatments.t4': 'إرشاد للأهل',
      'treatments.t5': 'تقييم ومتابعة طبية',
      'treatments.t6': 'مشاكل التنفس والحساسية',
      'treatments.t7': 'التهابات وأمراض الأطفال',
      'treatments.t8': 'اضطرابات الانتباه والتركيز',
      'treatments.s3_eyebrow': 'كيف نعمل',
      'treatments.s3_title': 'استجابة طبية بنهج شخصي',
      'treatments.s3_desc': 'لا ينتهي العلاج بالفحص فقط. الهدف هو فهم احتياجات الطفل، وشرح الصورة للأهل، وبناء طريق واضح للمضي قدماً.',
      'treatments.approach1_label': 'نهج شخصي:',
      'treatments.approach1_value': 'كل طفل وعائلة يتلقون معاملة مخصصة وإنسانية.',
      'treatments.approach2_label': 'الإصغاء للأهل:',
      'treatments.approach2_value': 'مكان للأسئلة والشرح والمشاركة الكاملة في العملية.',
      'treatments.approach3_label': 'استجابة مهنية:',
      'treatments.approach3_value': 'فحص معمّق وتفكير واسع ومرافقة حسب الحاجة.',
      'treatments.cta_title': 'تحتاجون مساعدة في اختيار مجال العلاج المناسب؟',
      'treatments.cta_desc': 'يمكنكم التواصل معنا وسنوجهكم للمسار الأنسب للطفل والعائلة.',
      'treatments.cta_contact': 'تواصل معنا',
      'treatments.cta_booking': 'لحجز موعد',

      /* ===== ADHD PAGE ===== */
      'adhd.page_title': 'اضطرابات الانتباه والتركيز | د. بسيم نموز',
      'adhd.page_desc': 'تشخيص ومرافقة وتوجيه مهني للأطفال والأهالي في مجال اضطرابات الانتباه والتركيز.',
      'adhd.hero_badge': 'تخصص خاص',
      'adhd.hero_h1': 'اضطرابات الانتباه والتركيز <span>تشخيص، مرافقة وتوجيه مهني</span>',
      'adhd.hero_subtitle': 'استجابة مهنية وحساسة ودقيقة للأهالي والأطفال الذين يواجهون أسئلة أو صعوبات أو اشتباهاً باضطراب الانتباه والتركيز.',
      'adhd.btn_assess': 'لتحديد تقييم أولي',
      'adhd.btn_signs': 'ما هي العلامات',
      'adhd.s1_eyebrow': 'نظرة شاملة',
      'adhd.s1_title': 'فهم الطفل، لا مجرد وضع تسمية',
      'adhd.s1_p1': 'يمكن أن تؤثر اضطرابات الانتباه والتركيز على مجالات عديدة في حياة الطفل. أحياناً تظهر الصعوبة في الإطار التعليمي، أحياناً في البيت، وأحياناً في العلاقات الاجتماعية أو التنظيم أو المثابرة أو التركيز أو الشعور بالكفاءة.',
      'adhd.s1_p2': 'عندما تظهر الأسئلة أو التساؤلات، من المهم اللجوء إلى استقصاء مهني ومنظم ومسؤول. الهدف ليس التسرع في لصق تسمية، بل فهم الطفل بعمق، وفحص الصورة الكاملة، وبناء الطريق المناسب والصحيح للمضي قدماً.',
      'adhd.signs_eyebrow': 'متى يجب المراجعة',
      'adhd.signs_title': 'علامات تستحق الانتباه',
      'adhd.sign1_title': 'صعوبة مستمرة في التركيز',
      'adhd.sign1_text': 'صعوبة في الجلوس لفترة طويلة، أو اتباع التعليمات أو إتمام المهام.',
      'adhd.sign2_title': 'تشتت عالٍ',
      'adhd.sign2_text': 'انتقال سريع بين المثيرات، صعوبة في الحفاظ على التسلسل والشعور العام بالتشتت.',
      'adhd.sign3_title': 'فرط الحركة أو الاندفاعية',
      'adhd.sign3_text': 'نشاط حركي مفرط، ردود فعل سريعة، صعوبة في الانتظار أو التوقف.',
      'adhd.sign4_title': 'صعوبة في التنظيم',
      'adhd.sign4_text': 'النسيان، فقدان الأشياء، صعوبة في إدارة الوقت أو تنظيم اليوم.',
      'adhd.sign5_title': 'فجوة بين القدرة والأداء',
      'adhd.sign5_text': 'الطفل ذكي وقادر، لكنه يجد صعوبة في تحقيق إمكاناته فعلياً.',
      'adhd.sign6_title': 'ملاحظات من الإطار التعليمي',
      'adhd.sign6_text': 'تنبيهات من المدرسة أو رياض الأطفال حول صعوبات الانتباه أو التنظيم أو السلوك.',
      'adhd.process_eyebrow': 'كيف تبدو العملية',
      'adhd.process_title': 'استقصاء، تقييم وتوجيه للمستقبل',
      'adhd.process_text': 'نهجي في هذا المجال مبني على فحص واسع ومنظم، يشمل التعرف على الطفل والعائلة، الإصغاء للصعوبات والأسئلة والأهداف، فهم أداء الطفل في البيت وفي الإطار التعليمي، التقييم المهني والمسؤول، والتوجيه للمستقبل وفق الحاجة.',
      'adhd.feat1_title': 'تشخيص مهني معمّق',
      'adhd.feat1_text': 'فحص منظم للصورة الكاملة قبل اتخاذ القرارات.',
      'adhd.feat2_title': 'مرافقة عائلية',
      'adhd.feat2_text': 'تقديم الشرح والتنظيم والتوجيه للأهل أيضاً، ليس للطفل فقط.',
      'adhd.feat3_title': 'تخطيط مخصص',
      'adhd.feat3_text': 'تكييف أفضل المسارات للطفل وفق احتياجاته وبيئته وأدائه.',
      'adhd.who_title': 'لمن يناسب المراجعة',
      'adhd.who1': 'أهل يتساءلون إذا كان الاستقصاء ضرورياً',
      'adhd.who2': 'عائلات تلقت ملاحظات من الإطار التعليمي',
      'adhd.who3': 'أطفال يجدون صعوبة في التركيز أو التنظيم',
      'adhd.who4': 'أهل يريدون فهم ما يمر به طفلهم بشكل أفضل',
      'adhd.cta_title': 'هل لديكم أسئلة أو تحتاجون تقييماً؟',
      'adhd.cta_desc': 'يمكن التواصل مع سكرتيرة العيادة عبر واتساب والحصول على توجيه منظم للمضي قدماً.',
      'adhd.cta_whatsapp': 'تواصل عبر واتساب',
      'adhd.cta_contact': 'لتفاصيل التواصل الكاملة',

      /* ===== DOCTORS PAGE ===== */
      'doctors.page_title': 'أطباء إضافيون | د. بسيم نموز',
      'doctors.page_desc': 'أطباء ومتخصصون إضافيون يمكنهم الانضمام مستقبلاً كمساحة مهنية أوسع.',
      'doctors.hero_badge': 'توسع مستقبلي',
      'doctors.hero_h1': 'أطباء إضافيون <span>ومساحة مهنية أوسع</span>',
      'doctors.hero_subtitle': 'بُني الموقع برؤية أوسع لكي يستطيع في المستقبل أن يضم أطباء ومتخصصين إضافيين، بهدف تقديم استجابة شاملة وعالية الجودة للعائلات في مكان واحد.',
      'doctors.btn_contact': 'للتواصل معنا',
      'doctors.btn_home': 'العودة للرئيسية',
      'doctors.s1_eyebrow': 'الرؤية',
      'doctors.s1_title': 'مكان مهني يمكنه أن ينمو معكم',
      'doctors.s1_desc': 'الهدف هو إنشاء مكان مهني وموثوق ومنظم حيث يمكن للعائلات إيجاد المعلومات والتوجيه والمتخصصين ذوي الجودة، مع الحفاظ على مستوى مهني عالٍ وشعور بالثقة.',
      'doctors.card1_title': 'تخصصات إضافية',
      'doctors.card1_text': 'أطباء ومتخصصون مكملون يمكنهم توسيع الاستجابة المقدمة للعائلات.',
      'doctors.card2_title': 'تعاون نوعي',
      'doctors.card2_text': 'العمل المشترك مع متخصصين تعرفهم وتثق بهم.',
      'doctors.card3_title': 'مظلة شاملة للعائلة',
      'doctors.card3_text': 'مكان واحد يجمع العلاج والمعلومات والتوجيه والإحالة لمتخصصين آخرين.',
      'doctors.future_eyebrow': 'قريباً',
      'doctors.future_title': 'هنا ستظهر في المستقبل بطاقات الأطباء',
      'doctors.future_desc': 'لكل طبيب سيكون هناك قسم مخصص باسمه وتخصصه ووصف مختصر وتفاصيل التواصل أو الانتقال للملف الكامل.',
      'doctors.coming_soon': 'أطباء إضافيون وتخصصات جديدة — قريباً',
      'doctors.cta_title': 'هل تريدون في المستقبل إضافة أطباء للموقع؟',
      'doctors.cta_desc': 'يمكن التواصل والبدء بالتخطيط لتوسيع الموقع كمساحة مهنية أوسع.',
      'doctors.cta_contact': 'للتواصل معنا',
      'doctors.cta_home': 'العودة للرئيسية'
    },

    en: {
      /* ===== META ===== */
      pageTitle: 'Magic Kids Institute | Directed by Dr. Baseem Namouz',
      pageDescription: 'Magic Kids Institute directed by Dr. Baseem Namouz. Comprehensive care for children and families, including ADHD assessment and compassionate medical guidance.',
      dir: 'ltr',

      /* ===== SHARED ===== */
      skip: 'Skip to main content',
      'header.logo_name': 'Magic Kids Institute',
      'header.logo_sub': 'Directed by Dr. Baseem Namouz',
      'header.dr_name': 'Dr. Baseem Namouz',
      'header.dr_sub': 'Pediatric Specialist',

      /* ===== NAV ===== */
      'nav.home': 'Home',
      'nav.about': 'About',
      'nav.treatments': 'Services',
      'nav.vision': 'Why us',
      'nav.services': 'Services',
      'nav.director': 'About',
      'nav.adhd': 'ADHD',
      'nav.portal': 'Patient Portal',
      'nav.contact': 'Contact',
      'nav.about_dr': 'About Dr. Baseem',
      'nav.adhd_full': 'ADHD Disorders',
      'nav.booking': 'Book an appointment',

      /* ===== FOOTER (common) ===== */
      'footer.logo_name': 'Magic Kids Institute',
      'footer.logo_sub': 'Directed by Dr. Baseem Namouz',
      'footer.dr_name': 'Dr. Baseem Namouz',
      'footer.dr_sub': 'Pediatric Specialist',
      'footer.desc': 'A place that connects professional medical guidance, a human approach, and convenient digital access for parents and patients.',
      'footer.nav_title': 'Quick links',
      'footer.contact_title': 'Contact',
      'footer.whatsapp': 'Secretary WhatsApp',
      'footer.portal': 'Enter patient portal',
      'footer.copy': '© 2026 Magic Kids Institute. All rights reserved.',
      'footer.copy_dr': '© 2026 Dr. Baseem Namouz. All rights reserved.',
      'footer.nav_home': 'Home',
      'footer.nav_about': 'About',
      'footer.nav_adhd': 'ADHD',
      'footer.nav_portal': 'Patient Portal',
      'footer.nav_treatments': 'Services',
      'footer.nav_contact': 'Contact',
      'footer.contact_section': 'Get in touch',

      /* ===== INDEX PAGE ===== */
      'hero.badge': 'Magic Kids Institute',
      'hero.title': 'Magic Kids Institute <span>Directed by Dr. Baseem Namouz</span>',
      'hero.subtitle': 'A professional, respectful and welcoming space for children and families, with comprehensive medical support and easy access to the patient portal.',
      'hero.booking': 'Book an appointment',
      'hero.portal': 'Patient Portal',
      'hero.director': 'Meet Dr. Baseem',
      'trust.one_number': 'Care',
      'trust.one_label': 'for every family',
      'trust.two_number': 'Support',
      'trust.two_label': 'for ADHD care',
      'trust.three_number': 'Approach',
      'trust.three_label': 'professional and kind',
      'trust.four_number': 'Access',
      'trust.four_label': 'to the patient portal',
      'vision.eyebrow': 'Our vision',
      'vision.title': 'A place that blends expertise, listening and trust',
      'vision.desc': 'Magic Kids Institute was created to give children and parents calm, clear guidance, and a reliable path to care, assessment and long-term support.',
      'vision.card1_title': 'Warm and respectful care',
      'vision.card1_text': 'Every child and every parent receives genuine attention, calm guidance and clear explanations.',
      'vision.card2_title': 'Accurate professional support',
      'vision.card2_text': 'Assessment, treatment and medical guidance grounded in responsibility, experience and a broad understanding of each family\'s needs.',
      'vision.card3_title': 'Fast and easy access',
      'vision.card3_text': 'Book appointments, contact the clinic, and enter the patient portal clearly and comfortably from any device.',
      'services.eyebrow': 'What we offer',
      'services.title': 'Main areas of care',
      'services.desc': 'The institute combines medical guidance, professional assessment, close family communication and a thoughtful approach for children and teens.',
      'services.item1': 'General pediatrics',
      'services.item2': 'ADHD assessment',
      'services.item3': 'Family guidance',
      'services.item4': 'Follow-up and developmental checks',
      'services.item5': 'Personal medical guidance',
      'services.item6': 'Digital patient portal access',
      'services.card1_text': 'Primary medical support, routine checkups and professional guidance for children at every stage.',
      'services.card2_text': 'Comprehensive assessment with a sensitive and accurate view of the child at home and in educational settings.',
      'services.card3_text': 'Clear communication, calm guidance and practical tools that strengthen the whole family.',
      'services.card4_text': 'Structured follow-up of growth, development and medical needs over time.',
      'services.card5_text': 'A clear and personalized plan forward, with precise answers to parents\' questions.',
      'services.card6_text': 'Simple, convenient and clear access to the patient system from any device at any time.',
      'director.quote_title': 'Our approach',
      'director.quote_text': 'Good pediatric care begins with listening, trust, and the feeling that someone is truly walking with you every step of the way.',
      'director.quote_signature': 'Magic Kids Institute directed by Dr. Baseem Namouz',
      'director.eyebrow': 'Directed by Dr. Baseem Namouz',
      'director.title': 'Medical leadership with a human heart',
      'director.text1': 'Dr. Baseem Namouz leads the institute with a vision that combines medical professionalism, personal care, and a respectful, clear process for every child and parent.',
      'director.text2': 'The institute is designed to be a safe, elegant and accessible place where families can receive medical support, ADHD-related care and ongoing guidance.',
      'director.tag1': 'Pediatric specialist',
      'director.tag2': 'Personal guidance',
      'director.tag3': 'Family support',
      'director.tag4': 'ADHD care',
      'contact.title': 'Would you like to contact the clinic?',
      'contact.desc': 'You can book an appointment, send a WhatsApp message to the clinic secretary, enter the patient portal, or call us with any question.',
      'contact.whatsapp': 'Book on WhatsApp',
      'contact.portal': 'Patient Portal',
      'contact.phone_label': 'Phone:',
      'contact.mail_label': 'Email:',
      'contact.address_label': 'Address:',
      'contact.address_value': '21 Tawfiq Ziad Street, Shefa-Amr',
      'contact.hours_label': 'Coordination:',
      'contact.hours_value': 'By prior arrangement through the secretary',

      /* ===== ABOUT PAGE ===== */
      'about.page_title': 'About Dr. Baseem Namouz | Pediatric Specialist',
      'about.page_desc': 'About Dr. Baseem Namouz, a pediatric specialist with a personal, professional and compassionate approach to children and families.',
      'about.hero_badge': 'About',
      'about.hero_h1': 'About <span>Dr. Baseem Namouz</span>',
      'about.hero_subtitle': 'A pediatric specialist providing professional, personal and compassionate medical care for children and families, with a broad view of child and family health.',
      'about.s1_eyebrow': 'Professional background',
      'about.s1_title': 'Medicine that starts with listening',
      'about.s1_p1': 'I am Dr. Baseem Namouz, a pediatric specialist who believes that good medicine begins above all with listening, responsibility and personal connection with the child and family.',
      'about.s1_p2': 'Over the years I have accompanied children and families across a wide range of medical situations, with one clear goal: to provide professional, precise and humane care — care that does not focus only on the symptom, but sees the whole child.',
      'about.s1_p3': 'For me, every medical meeting is an opportunity to pause, understand, ask the right questions, and tailor the right response to the needs of the child and family. I believe in clear communication, eye-level explanations, and clarity that allows parents to feel safe, calm and fully involved in the process.',
      'about.s2_eyebrow': 'My approach',
      'about.s2_title': 'Professionalism, sensitivity and personal guidance',
      'about.card1_title': 'Genuine listening',
      'about.card1_text': 'Understanding what the child is going through, what concerns the parents, and what really needs to happen to help.',
      'about.card2_title': 'Thorough examination',
      'about.card2_text': 'Looking at the full picture, thinking broadly, and acting with professional responsibility.',
      'about.card3_title': 'Eye-level explanation',
      'about.card3_text': 'Giving parents a sense of security, order and understanding, so they can make decisions calmly.',
      'about.s3_eyebrow': 'Areas of practice',
      'about.s3_title': 'Broad medical support',
      'about.t1': 'General pediatrics',
      'about.t2': 'Parental consultation and guidance',
      'about.t3': 'Medical assessment and follow-up',
      'about.t4': 'ADHD diagnosis and accompaniment',
      'about.cta_title': 'Would you like to book an appointment or ask a question?',
      'about.cta_desc': 'You can contact the clinic secretary by WhatsApp, phone or email — we are happy to help.',
      'about.cta_whatsapp': 'Book on WhatsApp',
      'about.cta_contact': 'Full contact details',

      /* ===== CONTACT PAGE ===== */
      'contact_page.page_title': 'Contact | Dr. Baseem Namouz',
      'contact_page.page_desc': 'Contact Dr. Baseem Namouz, clinic details, reception hours and appointment coordination through the clinic secretary.',
      'contact_page.hero_badge': 'Contact us',
      'contact_page.hero_h1': 'You can reach us <span>easily and conveniently</span>',
      'contact_page.hero_subtitle': 'To book an appointment, ask a general medical question or make an initial inquiry, contact the clinic secretary by WhatsApp, phone or email.',
      'contact_page.btn_whatsapp': 'Contact via WhatsApp',
      'contact_page.btn_call': 'Call now',
      'contact_page.s1_eyebrow': 'Clinic details',
      'contact_page.s1_title': 'All information in one place',
      'contact_page.card1_title': 'WhatsApp the secretary',
      'contact_page.card1_text': 'To book an appointment, send a WhatsApp message to the clinic secretary.',
      'contact_page.card2_title': 'Phone',
      'contact_page.card2_text': 'You can also reach us by phone during working hours.',
      'contact_page.card3_title': 'Email',
      'contact_page.card3_text': 'For questions, inquiries and updates.',
      'contact_page.loc_eyebrow': 'Location',
      'contact_page.loc_title': 'Clinic address',
      'contact_page.loc_address': '21 Tawfiq Ziad Street, Shefa-Amr',
      'contact_page.info_address_label': 'Address:',
      'contact_page.info_address_value': '21 Tawfiq Ziad Street, Shefa-Amr',
      'contact_page.info_appt_label': 'Appointment coordination:',
      'contact_page.info_appt_value': 'Through clinic secretary via WhatsApp or Maccabi website',
      'contact_page.info_email_label': 'Email:',
      'contact_page.hours_title': 'Reception hours',
      'contact_page.day1': 'Sunday',
      'contact_page.day1_hours': 'Closed',
      'contact_page.day2': 'Monday',
      'contact_page.day2_hours': '09:00–16:00',
      'contact_page.day3': 'Tuesday',
      'contact_page.day3_hours': '16:00–20:00',
      'contact_page.day4': 'Wednesday',
      'contact_page.day4_hours': '16:00–20:00',
      'contact_page.day5': 'Thursday',
      'contact_page.day5_hours': '17:00–20:00',
      'contact_page.day6': 'Friday',
      'contact_page.day6_hours': '09:30–12:30',
      'contact_page.day7': 'Saturday',
      'contact_page.day7_hours': '09:30–12:30',
      'contact_page.cta_title': 'Want us to get back to you?',
      'contact_page.cta_desc': 'The quickest way is to send a WhatsApp message to the clinic secretary. You can also contact us through the Maccabi website.',
      'contact_page.cta_whatsapp': 'Send a WhatsApp message',
      'contact_page.cta_email': 'Send an email',

      /* ===== BOOKING PAGE ===== */
      'booking.page_title': 'Book an Appointment | Dr. Baseem Namouz',
      'booking.page_desc': 'Book an appointment with Dr. Baseem Namouz through the clinic secretary via WhatsApp or the Maccabi website.',
      'booking.hero_badge': 'Book an appointment',
      'booking.hero_h1': 'Book an appointment <span>simply and clearly</span>',
      'booking.hero_subtitle': 'To book an appointment, send a WhatsApp message to the clinic secretary. You can also contact us via the Maccabi website or by phone.',
      'booking.btn_whatsapp': 'Book on WhatsApp',
      'booking.btn_call': 'Call the clinic',
      'booking.s1_eyebrow': 'How to book',
      'booking.s1_title': 'Three simple steps',
      'booking.card1_title': 'Contact the secretary',
      'booking.card1_text': 'Send a WhatsApp message to the clinic secretary with the child\'s name and reason for the visit.',
      'booking.card2_title': 'Get guidance',
      'booking.card2_text': 'The secretary will help choose the right track and complete the coordination details.',
      'booking.card3_title': 'Set a date',
      'booking.card3_text': 'The appointment is set according to clinic reception hours and by prior arrangement.',
      'booking.s2_eyebrow': 'Coordination options',
      'booking.s2_title': 'How would you like to reach us',
      'booking.info_wa_label': 'WhatsApp the secretary:',
      'booking.info_phone_label': 'Phone:',
      'booking.info_email_label': 'Email:',
      'booking.info_maccabi_label': 'Via Maccabi:',
      'booking.info_maccabi_value': 'You can also contact us via the Maccabi website.',
      'booking.hours_title': 'Reception hours',
      'booking.day1': 'Sunday',
      'booking.day1_hours': 'Closed',
      'booking.day2': 'Monday',
      'booking.day2_hours': '09:00–16:00',
      'booking.day3': 'Tuesday',
      'booking.day3_hours': '16:00–20:00',
      'booking.day4': 'Wednesday',
      'booking.day4_hours': '16:00–20:00',
      'booking.day5': 'Thursday',
      'booking.day5_hours': '17:00–20:00',
      'booking.day6': 'Friday',
      'booking.day6_hours': '09:30–12:30',
      'booking.day7': 'Saturday',
      'booking.day7_hours': '09:30–12:30',
      'booking.cta_title': 'Ready to book?',
      'booking.cta_desc': 'The quickest way is to send a WhatsApp message to the clinic secretary.',
      'booking.cta_whatsapp': 'Book on WhatsApp',
      'booking.cta_contact': 'Contact us',

      /* ===== CLINICFLOW PAGE ===== */
      'clinicflow.page_title': 'Patient Portal | System Login',
      'clinicflow.page_desc': 'Access the patient portal and ClinicFlow system for appointment management, staff login, and patient login through one interface.',
      'clinicflow.hero_badge': 'Patient Portal',
      'clinicflow.hero_h1': 'Quick access <span>to the patient portal</span>',
      'clinicflow.hero_subtitle': 'The ClinicFlow system allows staff and patients to enter one system for managing appointments, viewing visit details, and performing actions simply and conveniently.',
      'clinicflow.btn_enter': 'Enter the system',
      'clinicflow.btn_booking': 'Book an appointment',
      'clinicflow.s1_eyebrow': 'What you can do in the system',
      'clinicflow.s1_title': 'One system for two types of users',
      'clinicflow.card1_title': 'Staff login',
      'clinicflow.card1_text': 'Access appointment management, view patients, update statuses and manage daily tasks.',
      'clinicflow.card2_title': 'Patient login',
      'clinicflow.card2_text': 'Independent access to view appointments, request a code via WhatsApp and quick verification.',
      'clinicflow.card3_title': 'WhatsApp verification',
      'clinicflow.card3_text': 'The patient system works with a one-time code via WhatsApp, making login simple and accessible.',
      'clinicflow.s2_eyebrow': 'Tested in practice',
      'clinicflow.s2_title': 'What has been tested in the system',
      'clinicflow.check1_label': 'Staff login:',
      'clinicflow.check1_value': 'Tested and working',
      'clinicflow.check2_label': 'Patient login:',
      'clinicflow.check2_value': 'Tested and working',
      'clinicflow.check3_label': 'Code sending:',
      'clinicflow.check3_value': 'Works via WhatsApp',
      'clinicflow.check4_label': 'Interface:',
      'clinicflow.check4_value': 'Includes staff track and patient track',
      'clinicflow.steps_title': 'How to use',
      'clinicflow.step1_label': 'Step 1',
      'clinicflow.step1_value': 'Enter the system',
      'clinicflow.step2_label': 'Step 2',
      'clinicflow.step2_value': 'Choose staff or patient',
      'clinicflow.step3_label': 'Step 3',
      'clinicflow.step3_value': 'Receive verification code',
      'clinicflow.step4_label': 'Step 4',
      'clinicflow.step4_value': 'Login and perform the desired action',
      'clinicflow.cta_title': 'Want to enter the patient portal now?',
      'clinicflow.cta_desc': 'You can go directly to the system from here, or contact us if you need help logging in.',
      'clinicflow.cta_enter': 'Enter the system',
      'clinicflow.cta_help': 'Need help?',

      /* ===== TREATMENTS PAGE ===== */
      'treatments.page_title': 'Services | Dr. Baseem Namouz',
      'treatments.page_desc': 'Dr. Baseem Namouz\'s services: pediatrics, parental counseling, medical follow-up, and ADHD disorders.',
      'treatments.hero_badge': 'Services',
      'treatments.hero_h1': 'Broad medical support <span>for children and families</span>',
      'treatments.hero_subtitle': 'The site brings together a variety of medical services and support areas for children and families, with the goal of providing quality, clear and personalized care.',
      'treatments.btn_booking': 'Book an appointment',
      'treatments.btn_contact': 'Contact us',
      'treatments.s1_eyebrow': 'Professional umbrella',
      'treatments.s1_title': 'Main services at the clinic',
      'treatments.card1_title': 'General pediatrics',
      'treatments.card1_text': 'Checkups, assessments, medical guidance and professional support for common childhood conditions.',
      'treatments.card2_title': 'Parental counseling',
      'treatments.card2_text': 'Professional guidance in clear, accessible language to help parents understand the situation and make confident decisions.',
      'treatments.card3_title': 'Medical follow-up',
      'treatments.card3_text': 'Long-term accompaniment in situations requiring monitoring, review, follow-up appointments and adjustment of the treatment path.',
      'treatments.card4_title': 'ADHD disorders',
      'treatments.card4_text': 'Assessment, evaluation and accompaniment for ADHD, with a broad view of the child, family and functioning.',
      'treatments.s2_eyebrow': 'Areas of practice',
      'treatments.s2_title': 'What you can consult us about',
      'treatments.t1': 'General pediatrics',
      'treatments.t2': 'Vaccinations and preventive counseling',
      'treatments.t3': 'Routine checkups and growth monitoring',
      'treatments.t4': 'Parental counseling',
      'treatments.t5': 'Medical assessment and follow-up',
      'treatments.t6': 'Respiratory problems and allergies',
      'treatments.t7': 'Infections and childhood illnesses',
      'treatments.t8': 'ADHD disorders',
      'treatments.s3_eyebrow': 'How we work',
      'treatments.s3_title': 'Medical support with a personal approach',
      'treatments.s3_desc': 'Care does not end with the examination. The goal is to understand the child\'s needs, explain the picture to parents, and build a clear path forward.',
      'treatments.approach1_label': 'Personal approach:',
      'treatments.approach1_value': 'Every child and family receives tailored and humane care.',
      'treatments.approach2_label': 'Listening to parents:',
      'treatments.approach2_value': 'A place for questions, explanations and full partnership in the process.',
      'treatments.approach3_label': 'Professional response:',
      'treatments.approach3_value': 'Thorough examination, broad thinking and support as needed.',
      'treatments.cta_title': 'Need help choosing the right area of care?',
      'treatments.cta_desc': 'Contact us and we will guide you to the most suitable track for your child and family.',
      'treatments.cta_contact': 'Contact us',
      'treatments.cta_booking': 'Book an appointment',

      /* ===== ADHD PAGE ===== */
      'adhd.page_title': 'ADHD Disorders | Dr. Baseem Namouz',
      'adhd.page_desc': 'Diagnosis, accompaniment and professional guidance for children and families in the field of ADHD disorders.',
      'adhd.hero_badge': 'Special expertise',
      'adhd.hero_h1': 'ADHD disorders <span>assessment, accompaniment and professional guidance</span>',
      'adhd.hero_subtitle': 'Professional, sensitive and precise support for parents and children facing questions, difficulties or suspected ADHD.',
      'adhd.btn_assess': 'Book an initial assessment',
      'adhd.btn_signs': 'What are the signs',
      'adhd.s1_eyebrow': 'Broad perspective',
      'adhd.s1_title': 'Understand the child, not just the label',
      'adhd.s1_p1': 'ADHD can affect many areas of a child\'s life. Sometimes the difficulty appears in the educational setting, sometimes at home, and sometimes in social relationships, organization, persistence, concentration or sense of capability.',
      'adhd.s1_p2': 'When questions or uncertainties arise, it is important to seek professional, structured and responsible clarification. The goal is not to rush to attach a label, but to understand the child deeply, examine the full picture, and build a suitable and correct path forward.',
      'adhd.signs_eyebrow': 'When to seek help',
      'adhd.signs_title': 'Signs to pay attention to',
      'adhd.sign1_title': 'Persistent difficulty concentrating',
      'adhd.sign1_text': 'Difficulty sitting for extended periods, following instructions or completing tasks.',
      'adhd.sign2_title': 'High distractibility',
      'adhd.sign2_text': 'Rapid switching between stimuli, difficulty maintaining sequence and a general sense of dispersion.',
      'adhd.sign3_title': 'Restlessness or impulsivity',
      'adhd.sign3_text': 'Increased movement, quick reactions, difficulty waiting or stopping.',
      'adhd.sign4_title': 'Organizational difficulties',
      'adhd.sign4_text': 'Forgetfulness, losing items, difficulty managing time or daily routine.',
      'adhd.sign5_title': 'Gap between ability and performance',
      'adhd.sign5_text': 'The child is smart and capable but struggles to realize their potential in practice.',
      'adhd.sign6_title': 'Feedback from educational settings',
      'adhd.sign6_text': 'Comments from school or kindergarten about attention difficulties, organization or behavior.',
      'adhd.process_eyebrow': 'What the process looks like',
      'adhd.process_title': 'Clarification, assessment and guidance forward',
      'adhd.process_text': 'My approach in this field is based on a broad and structured evaluation, including getting to know the child and family, listening to difficulties, questions and goals, understanding the child\'s functioning at home and in educational settings, responsible professional assessment, and guidance forward according to need.',
      'adhd.feat1_title': 'Professional in-depth diagnosis',
      'adhd.feat1_text': 'Structured examination of the full picture before making decisions.',
      'adhd.feat2_title': 'Family accompaniment',
      'adhd.feat2_text': 'Providing explanation, structure and guidance to parents too, not just the child.',
      'adhd.feat3_title': 'Personalized planning',
      'adhd.feat3_text': 'Adapting the best path for the child according to their needs, environment and functioning.',
      'adhd.who_title': 'Who should seek help',
      'adhd.who1': 'Parents wondering if clarification is needed',
      'adhd.who2': 'Families who received feedback from an educational setting',
      'adhd.who3': 'Children who struggle to concentrate or organize',
      'adhd.who4': 'Parents who want to better understand what their child is going through',
      'adhd.cta_title': 'Have questions or need an assessment?',
      'adhd.cta_desc': 'You can contact the clinic secretary via WhatsApp and receive structured guidance forward.',
      'adhd.cta_whatsapp': 'Contact via WhatsApp',
      'adhd.cta_contact': 'Full contact details',

      /* ===== DOCTORS PAGE ===== */
      'doctors.page_title': 'Additional Doctors | Dr. Baseem Namouz',
      'doctors.page_desc': 'Additional doctors and professionals who may join the site in the future as a broader professional space.',
      'doctors.hero_badge': 'Future expansion',
      'doctors.hero_h1': 'Additional doctors <span>and a broader professional space</span>',
      'doctors.hero_subtitle': 'The site was built with a broader vision so that it can include additional doctors and professionals in the future, in order to give families comprehensive, quality and organized support in one place.',
      'doctors.btn_contact': 'Contact us',
      'doctors.btn_home': 'Back to home',
      'doctors.s1_eyebrow': 'The vision',
      'doctors.s1_title': 'A professional space that can grow with you',
      'doctors.s1_desc': 'The goal is to create a professional, reliable and organized place where families can find information, guidance and quality professionals, while maintaining a high professional standard and a sense of trust.',
      'doctors.card1_title': 'Additional specialties',
      'doctors.card1_text': 'Complementary doctors and professionals who can broaden the support available to families.',
      'doctors.card2_title': 'Quality collaborations',
      'doctors.card2_text': 'Working together with professionals you know and trust.',
      'doctors.card3_title': 'A broad umbrella for families',
      'doctors.card3_text': 'One place that connects care, information, guidance and referral to additional professionals.',
      'doctors.future_eyebrow': 'Coming soon',
      'doctors.future_title': 'Doctor cards will appear here in the future',
      'doctors.future_desc': 'Each doctor will have a dedicated area with their name, specialty, a brief description and contact details or a link to their full profile.',
      'doctors.coming_soon': 'Additional doctors and new specialties — coming soon',
      'doctors.cta_title': 'Would you like to add doctors to the site in the future?',
      'doctors.cta_desc': 'Contact us and start planning the expansion of the site into a broader professional space.',
      'doctors.cta_contact': 'Contact us',
      'doctors.cta_home': 'Back to home'
    }
  };

  let currentTheme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
  let currentLanguage = 'he';
  let isMenuOpen = false;

  root.setAttribute('data-theme', currentTheme);

  function updateThemeIcon() {
    if (!themeToggle) return;
    if (currentTheme === 'dark') {
      themeToggle.innerHTML = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>';
      themeToggle.setAttribute('aria-label', currentLanguage === 'en' ? 'Switch to light mode' : currentLanguage === 'ar' ? 'الانتقال إلى الوضع الفاتح' : 'החלף למצב בהיר');
    } else {
      themeToggle.innerHTML = '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';
      themeToggle.setAttribute('aria-label', currentLanguage === 'en' ? 'Switch to dark mode' : currentLanguage === 'ar' ? 'الانتقال إلى الوضع الداكن' : 'החלף למצב כהה');
    }
  }

  function applyLanguage(lang) {
    const selected = translations[lang] || translations.he;
    currentLanguage = lang;
    document.documentElement.lang = lang;
    document.documentElement.dir = selected.dir;
    document.title = selected.pageTitle;

    const descriptionTag = document.querySelector('meta[name="description"]');
    const ogTitle = document.querySelector('meta[property="og:title"]');
    const ogDescription = document.querySelector('meta[property="og:description"]');
    if (descriptionTag) descriptionTag.setAttribute('content', selected.pageDescription);
    if (ogTitle) ogTitle.setAttribute('content', selected.pageTitle);
    if (ogDescription) ogDescription.setAttribute('content', selected.pageDescription);

    document.querySelectorAll('[data-i18n]').forEach(function (element) {
      var key = element.getAttribute('data-i18n');
      var value = selected[key];
      if (!value) return;
      if (element.hasAttribute('data-i18n-html')) {
        element.innerHTML = value;
      } else {
        element.textContent = value;
      }
    });

    langButtons.forEach(function (button) {
      button.classList.toggle('is-active', button.dataset.langSwitch === lang);
    });

    updateThemeIcon();
  }

  function toggleMenu() {
    if (!mobileNav || !mobileMenuBtn) return;
    isMenuOpen = !isMenuOpen;
    mobileNav.classList.toggle('is-open', isMenuOpen);
    mobileMenuBtn.setAttribute('aria-expanded', String(isMenuOpen));

    if (isMenuOpen) {
      mobileMenuBtn.innerHTML = '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>';
      document.body.style.overflow = 'hidden';
    } else {
      mobileMenuBtn.innerHTML = '<svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>';
      document.body.style.overflow = '';
    }
  }

  function handleScroll() {
    var scrollY = window.scrollY || window.pageYOffset;
    if (header) {
      header.classList.toggle('header--scrolled', scrollY > 20);
    }
  }

  function revealAllSections() {
    fadeElements.forEach(function (el, index) {
      window.setTimeout(function () {
        el.classList.add('is-visible');
      }, Math.min(index * 40, 320));
    });
  }

  updateThemeIcon();
  applyLanguage('he');

  if (themeToggle) {
    themeToggle.addEventListener('click', function () {
      currentTheme = currentTheme === 'dark' ? 'light' : 'dark';
      root.setAttribute('data-theme', currentTheme);
      updateThemeIcon();
    });
  }

  langButtons.forEach(function (button) {
    button.addEventListener('click', function () {
      applyLanguage(button.dataset.langSwitch || 'he');
    });
  });

  if (mobileMenuBtn) {
    mobileMenuBtn.addEventListener('click', toggleMenu);
  }

  if (mobileNav) {
    mobileNav.querySelectorAll('a').forEach(function (link) {
      link.addEventListener('click', function () {
        if (isMenuOpen) toggleMenu();
      });
    });
  }

  window.addEventListener('scroll', handleScroll, { passive: true });
  handleScroll();
  revealAllSections();
  window.addEventListener('load', revealAllSections);
  window.addEventListener('pageshow', revealAllSections);

  if (window.matchMedia('(prefers-reduced-motion: reduce)').matches || !('IntersectionObserver' in window)) {
    fadeElements.forEach(function (el) { el.classList.add('is-visible'); });
  }

  setTimeout(function () {
    fadeElements.forEach(function (el) { el.classList.add('is-visible'); });
  }, 800);

  document.addEventListener('visibilitychange', function () {
    if (!document.hidden) {
      fadeElements.forEach(function (el) { el.classList.add('is-visible'); });
    }
  });

  document.querySelectorAll('a[href^="#"]').forEach(function (anchor) {
    anchor.addEventListener('click', function (e) {
      var targetId = this.getAttribute('href');
      if (!targetId || targetId === '#') return;
      var target = document.querySelector(targetId);
      if (target) {
        e.preventDefault();
        target.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    });
  });
})();
