(function(){
 const copy={he:['שתפו חוות דעת','חוות דעת ותמונות','נשלח לאישור לפני פרסום','כתיבת חוות דעת','שיתוף תמונה','סגירה','פתיחה בעמוד מלא'],ar:['شاركوا تجربتكم','آراؤكم وصوركم','تُرسل للموافقة قبل النشر','كتابة رأي','مشاركة صورة','إغلاق','فتح بصفحة كاملة'],en:['Share your experience','Reviews and photos','Sent for approval before publication','Write a review','Share a photo','Close','Open in a full page']};
 const dialog=document.getElementById('community-dialog'),launch=document.getElementById('community-launch');if(!dialog||!launch)return;let active='reviews';
 function language(){return document.documentElement.lang in copy?document.documentElement.lang:'ar';}
 function show(kind,focus){active=kind;const t=copy[language()];['reviews','gallery'].forEach(k=>{const tab=document.getElementById('community-tab-'+k);tab.setAttribute('aria-selected',String(k===kind));tab.tabIndex=k===kind?0:-1;document.getElementById('community-panel-'+k).hidden=k!==kind;});const frame=document.getElementById(kind+'-frame'),url='https://app.magickidsinstitute.com/'+kind+'?lang='+language();if(!frame.getAttribute('src'))frame.src=url;document.getElementById('community-full').href=frame.src;if(focus)document.getElementById('community-tab-'+kind).focus();}
 function render(){const t=copy[language()];['community-launch-text','community-title','community-note','community-tab-reviews','community-tab-gallery'].forEach((id,i)=>document.getElementById(id).textContent=t[i]);document.getElementById('community-close').setAttribute('aria-label',t[5]);document.getElementById('community-full').textContent=t[6];document.getElementById('reviews-frame').title=t[3];document.getElementById('gallery-frame').title=t[4];}
 launch.addEventListener('click',()=>{dialog.showModal();show(active,false);document.getElementById('community-close').focus();});document.getElementById('community-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>launch.focus());
 ['reviews','gallery'].forEach(kind=>{const tab=document.getElementById('community-tab-'+kind);tab.addEventListener('click',()=>show(kind,false));tab.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();show(e.key==='Home'?'reviews':e.key==='End'?'gallery':active==='reviews'?'gallery':'reviews',true);}});});render();document.addEventListener('magic-language',render);
})();
