import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';
import {copy, activities} from '../src/copy.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const version='20260909-sarah-moxo-1';
const origin='https://magickidsinstitute.com';
const languages=['he','ar','en'];
const texts=JSON.parse(fs.readFileSync(path.join(root,'src/translations.json'),'utf8'));
const strip=s=>s.replace(/<br\s*\/?\s*>/gi,' ').replace(/<[^>]*>/g,'');
for(const lang of languages)for(const key in texts[lang])texts[lang][key]=strip(texts[lang][key]);
for(const [key,values] of Object.entries(copy))languages.forEach((lang,i)=>texts[lang][key]=values[i]);
activities.forEach(([id,...v])=>languages.forEach((lang,i)=>{texts[lang]['a.'+id]=v[i];texts[lang]['a.'+id+'.desc']=v[i+3];}));
const used=new Set();
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
function value(key,lang='ar'){used.add(key);if(!texts[lang]?.[key])throw Error('Missing '+lang+' '+key);return texts[lang][key];}
const t=(key,tag='span',attrs='')=>`<${tag} data-i18n="${key}" ${attrs}>${esc(value(key))}</${tag}>`;
const link=(url,key,cls='button',attrs='')=>`<a class="${cls}" href="${esc(url)}" ${attrs}>${t(key)}<span aria-hidden="true" class="arrow">↗</span></a>`;
const pill=key=>t(key,'span','class="pill"');
const bookingUrl=clinic=>clinic==='adhd'?'https://magickids-panel.vercel.app/onboarding/public':'https://app.magickidsinstitute.com/book/pediatrics';
const buttons=()=>`<div class="actions">${link(bookingUrl('pediatrics'),'u.bookPeds')}${link(bookingUrl('adhd'),'u.bookAdhd','button outline')}${link('/index.html#moxo','u.moxoBook','text-link')}</div>`;
const pediatricsPhones=()=>`<div class="clinic-phones"><a href="https://wa.me/972543496656">${t('u.pedsPhone')}<b dir="ltr">054-349-6656</b></a><a href="tel:+97248717911">${t('u.pedsSecretary')}<b dir="ltr">04-871-7911</b></a></div>`;
const clinicCards=()=>`<div class="cards two clinic-options"><article class="card"><span class="number" aria-hidden="true">01</span>${t('u.bookPeds','h3')}${t('u.pedsCalendar','p')}${link(bookingUrl('pediatrics'),'u.bookPeds')}${pediatricsPhones()}</article><article class="card"><span class="number" aria-hidden="true">02</span>${t('u.bookAdhd','h3')}${t('u.adhdCalendar','p')}${link(bookingUrl('adhd'),'u.bookAdhd','button outline')}</article></div>${t('u.bookingConfirmation','p','class="fine"')}`;
const section=(eyebrow,title,body,id='',cls='')=>`<section ${id?`id="${id}"`:''} class="section ${cls}"><div class="wrap"><div class="section-heading">${eyebrow?t(eyebrow,'p','class="eyebrow"'):''}${t(title,'h2')}</div>${body}</div></section>`;
function cards(prefix,count,title='title',body='text'){return `<div class="cards three">${Array.from({length:count},(_,i)=>`<article class="card"><span class="number" aria-hidden="true">0${i+1}</span>${t(prefix+(i+1)+'_'+title,'h3')}${t(prefix+(i+1)+'_'+body,'p')}</article>`).join('')}</div>`;}
const photo=(cls='portrait')=>`<figure class="${cls}"><img src="assets/doctor.jpg" width="700" height="830" alt="${esc(value('u.photo'))}" data-i18n-alt="u.photo" fetchpriority="high"><figcaption>${t('header.dr_name','b')}${t('header.dr_sub','span')}</figcaption></figure>`;
function hero(eyebrow,title,desc,extra='',portrait=false){return `<section class="page-hero"><div class="wrap ${portrait?'hero-grid':''}"><div>${t(eyebrow,'p','class="eyebrow"')}${t(title,'h1')}${t(desc,'p','class="lead"')}${extra}</div>${portrait?photo():''}</div></section>`;}
function medicalCards(){return `<div class="cards three">${Array.from({length:6},(_,i)=>`<article class="card service" id="service-${i+1}"><span class="number" aria-hidden="true">0${i+1}</span>${t('services.item'+(i+1),'h3')}${t('services.card'+(i+1)+'_text','p')}${link(i===1?'adhd.html':'treatments.html#medical','u.more','text-link')}</article>`).join('')}</div>`;}
function activityCards(limit=8){return `<div class="cards ${limit===4?'four':'four'}">${activities.slice(0,limit).map(([id],i)=>`<article class="card activity" id="${id}"><div class="card-top"><span class="number" aria-hidden="true">0${i+1}</span>${pill('m.planned')}</div>${t('a.'+id,'h3')}${t('a.'+id+'.desc','p')}${link('activities.html?activity='+id+'#enquiry','u.activityInterest','text-link')}</article>`).join('')}</div>`;}
function recruitStrip(){return `<section class="recruit-strip" id="join"><div class="wrap recruit-grid"><div>${t('m.join.eyebrow','p','class="eyebrow"')}${t('u.applicationTitle','h2')}${t('m.join.desc','p','class="lead"')}<div class="tags">${['m.join.chess','m.join.therapists','m.join.operators'].map(pill).join('')}</div><div class="actions">${link('recruit.html','m.join.apply','button yellow')}${link('assets/recruitment-banner.png','m.join.banner','text-link','download="magic-kids-recruitment.png"')}</div></div><aside>${t('m.join.idea','h3')}<ol class="steps">${[1,2,3].map(i=>t('m.join.step'+i,'li')).join('')}</ol></aside></div></section>`;}
function contacts(){return `<div class="cards two contact-cards"><article class="card">${t('u.pedsPhone','h3')}${pediatricsPhones()}</article><article class="card">${t('u.instituteContact','h3')}<a href="https://wa.me/972544020043" target="_blank" rel="noopener noreferrer" class="contact-number" dir="ltr">054-402-0043</a>${link('tel:+972544020043','booking.btn_call','text-link')}</article><article class="card">${t('contact.mail_label','h3')}<a class="email-address" href="mailto:magickids@magickidsinstitute.com" dir="ltr">magickids@magickidsinstitute.com</a>${t('m.contact.desc','p')}</article><article class="card">${t('m.contact.map','h3')}${t('contact.address_value','p')}${link('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent('תופיק זיאד 21 שפרעם'),'u.more','text-link','data-google-maps target="_blank" rel="noopener noreferrer"')}</article></div>`;}
function hours(){return `<article class="card hours">${t('booking.hours_title','h2')}<dl>${[1,2,3,4,5,6,7].map(i=>`<div>${t('booking.day'+i,'dt')}${t('booking.day'+i+'_hours','dd','dir="auto"')}</div>`).join('')}</dl>${t('u.hoursNote','p','class="fine"')}</article>`;}
function contactCTA(){return section('m.contact.eyebrow','u.contactTitle',`<div class="split-cta">${t('m.contact.desc','p','class="lead"')}<div class="actions">${link('booking.html','nav.booking')}${link('contact.html','nav.contact','button outline')}</div></div>`,'contact','soft');}
function enquiry(kind){return `<section id="enquiry" class="section"><div class="wrap form-wrap"><div>${t('u.formTitle','h2')}${t('u.formHelp','p')}${t('u.noMedical','p','class="fine"')}</div><form class="enquiry-form card" data-enquiry="${kind}">${t('u.required','p','class="fine"')}<div class="form-grid"><label>${t('u.name')} *<input name="name" autocomplete="name" maxlength="100" required></label><label>${t('u.phone')} *<input name="phone" autocomplete="tel" inputmode="tel" dir="ltr" type="tel" minlength="7" maxlength="25" required></label><label class="full">${t('u.email')} (${t('u.optional')})<input name="email" autocomplete="email" type="email" dir="ltr" maxlength="150"></label>${kind==='parent'?`<label class="full">${t('u.subject')}<select name="activity">${t('u.parentSubject','option','value="general"')}${activities.map(([id])=>t('a.'+id,'option',`value="${id}"`)).join('')}</select></label>`:''}<label class="full">${t(kind==='instructor'?'u.experience':'u.message')} (${t('u.optional')})<textarea name="message" rows="4" maxlength="900"></textarea></label></div><div class="actions"><button type="submit" disabled name="channel" value="email" class="button">${t('u.emailDraft')}</button><button type="submit" disabled name="channel" value="whatsapp" class="button outline">${t('u.waDraft')}</button></div><p class="form-status" role="status" aria-live="polite"></p></form></div></section>`;}
const servicesDetail=section('treatments.s2_eyebrow','u.allServices',`<div class="service-list">${Array.from({length:8},(_,i)=>`<a href="${i===7?'adhd.html':'booking.html'}"><span aria-hidden="true">${String(i+1).padStart(2,'0')}</span>${t('treatments.t'+(i+1))}<span class="arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`,'medical');
const appBody=hero('u.app','u.installTitle','u.installCopy',`<div class="actions"><button class="button yellow" data-install>${t('u.install')}</button>${link('booking.html','nav.booking','button outline')}</div>`,false)+section('u.tagline','u.app',`<div class="app-feature"><img src="assets/institute-logo.jpg" width="640" height="640" alt="${esc(value('u.logo'))}" data-i18n-alt="u.logo"><div class="cards two">${[1,2,3,4].map((i)=>link(['treatments.html','booking.html','index.html','https://magic-kids-hub.baseem-n.chatgpt.site/admin'][i-1],'u.appService'+i,'card app-link')).join('')}</div></div>`)+section('u.app','u.installHelp',`<div class="cards two"><article class="card"><h3>iPhone / iPad</h3>${t('u.ios','p')}</article><article class="card"><h3>Android</h3>${t('u.android','p')}</article></div>${t('u.appOffline','p','class="notice"')}`,'install-help');
const pages={
 'index':{title:'header.logo_name',desc:'u.servicesCopy',body:`<section class="home-hero"><div class="wrap hero-grid"><div>${t('m.location','p','class="eyebrow"')}<p class="bilingual-name"><span lang="he">מכון ילדי הקסם</span><span aria-hidden="true"> / </span><span lang="ar">معهد أطفال السحر</span></p><h1>${t('u.hero1')}<br>${t('u.hero2','em')}</h1>${t('m.hero.description','p','class="lead"')}${buttons()}${t('m.director.line','p','class="signature"')}<aside class="admin-entry">${t('u.adminTitle','h2')}${t('u.adminHelp','p')}<div class="actions">${link('https://magic-kids-hub.baseem-n.chatgpt.site/admin','u.adminTitle','button outline')}${link('https://app.magickidsinstitute.com/admin/intake','u.adhdAdmin','text-link')}</div></aside></div>${photo()}</div></section><div class="wrap pathways">${[['treatments.html','m.path.care','m.path.care.desc'],['activities.html','m.path.activities','m.path.activities.desc'],['recruit.html','m.path.join','m.path.join.desc']].map(([url,title,desc],i)=>`<a href="${url}"><span class="number">0${i+1}</span><div>${t(title,'h2')}${t(desc,'p')}</div><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}</div>`+section('u.moxoBook','u.moxoTitle',`<div class="cards two"><article class="card">${t('u.moxoWhat','p')}${t('u.moxoHow','h3')}${t('u.moxoSteps','p')}${link('https://moxo.ai/faq/','u.moxoSource','text-link','target="_blank" rel="noopener noreferrer"')}</article><article class="card">${t('u.moxoApproval','p','class="lead"')}${link('https://app.magickidsinstitute.com/moxo','u.moxoBook')}${t('u.sarahPolicy','p','class="fine"')}</article></div>`,'moxo','soft')+section('m.care.eyebrow','u.allServices',`${t('u.servicesCopy','p','class="section-intro"')}${medicalCards()}<div class="section-end">${link('treatments.html','m.care.all','text-link')}</div>`,'services')+section('m.activities.eyebrow','m.activities.title',`<div class="activity-intro"><div>${t('m.activities.ages','p','class="lead"')}${link('activities.html','m.activities.all','button')}${t('m.activities.note','p','class="fine"')}</div><img loading="lazy" src="assets/activity-illustration.png" alt="${esc(value('m.activities.art'))}" data-i18n-alt="m.activities.art" width="1536" height="1024"></div>${activityCards(4)}`,'activities','soft')+recruitStrip()+section('m.director.line','m.director.title',`<div class="split-cta">${t('director.text1','p','class="lead"')}${link('about.html','hero.director','button outline')}</div>`,'director')+section('m.workshop.eyebrow','u.workshopNew',`<div class="split-cta">${t('u.workshopCopy','p','class="lead"')}${link('workshop-register.html','m.workshop.cta','button outline')}</div>`,'workshop','soft')+section('m.contact.eyebrow','u.contactTitle',contacts(),'contact-home')+section('u.app','u.installTitle',`<div class="split-cta">${t('u.installCopy','p','class="lead"')}${link('app.html','u.installHelp','button')}</div>`,'app','soft')},
 'treatments':{title:'treatments.page_title',desc:'treatments.page_desc',body:hero('treatments.hero_badge','treatments.hero_h1','treatments.hero_subtitle',buttons())+section('treatments.s1_eyebrow','treatments.s1_title',medicalCards())+servicesDetail+section('treatments.s3_eyebrow','treatments.s3_title',`${t('treatments.s3_desc','p','class="section-intro"')}<div class="cards three">${[1,2,3].map(i=>`<article class="card">${t('treatments.approach'+i+'_label','h3')}${t('treatments.approach'+i+'_value','p')}</article>`).join('')}</div>`,'approach','soft')+contactCTA()},
 'about':{title:'about.page_title',desc:'about.page_desc',body:hero('about.hero_badge','about.hero_h1','about.hero_subtitle',buttons(),true)+section('about.s1_eyebrow','about.s1_title',`<div class="prose">${[1,2,3].map(i=>t('about.s1_p'+i,'p')).join('')}</div>`)+section('about.s2_eyebrow','about.s2_title',cards('about.card',3),'approach','soft')+servicesDetail+contactCTA()},
 'adhd':{title:'adhd.page_title',desc:'adhd.page_desc',body:hero('adhd.hero_badge','adhd.hero_h1','adhd.hero_subtitle',`<div class="actions">${link(bookingUrl('adhd'),'adhd.btn_assess')}${link('#signs','adhd.btn_signs','button outline')}</div>`)+section('adhd.s1_eyebrow','adhd.s1_title',`<div class="prose">${t('adhd.s1_p1','p')}${t('adhd.s1_p2','p')}</div>`)+section('adhd.signs_eyebrow','adhd.signs_title',cards('adhd.sign',6),'signs','soft')+section('adhd.process_eyebrow','adhd.process_title',`${t('adhd.process_text','p','class="section-intro"')}${cards('adhd.feat',3)}`)+section('adhd.hero_badge','adhd.who_title',`<ul class="simple-list">${[1,2,3,4].map(i=>t('adhd.who'+i,'li')).join('')}</ul>`,'who','soft')+contactCTA()},
 'activities':{title:'m.nav.activities',desc:'m.activities.ages',body:hero('m.activities.eyebrow','m.activities.title','m.activities.ages',link('#enquiry','u.activityInterest'))+section('m.activities.eyebrow','m.activities.all',`${t('u.activityDetails','p','class="notice"')}${activityCards()}`,'catalog')+enquiry('parent')+recruitStrip()},
 'recruit':{title:'m.path.join',desc:'u.recruitDetail',body:hero('m.join.eyebrow','u.applicationTitle','u.recruitDetail',`<div class="actions">${link('#enquiry','m.join.apply','button yellow')}${link('assets/recruitment-banner.png','m.join.banner','button outline','download="magic-kids-recruitment.png"')}</div>`)+section('m.join.eyebrow','m.join.idea',`<div class="recruit-detail"><div><div class="cards">${['chess','therapists','operators'].map((role,i)=>`<article class="card"><span class="number">0${i+1}</span>${t('m.join.'+role,'h3')}</article>`).join('')}</div>${t('u.recruitFit','p','class="lead"')}${t('m.join.note','p','class="fine"')}</div><img class="recruit-banner" loading="lazy" src="assets/recruitment-banner.png" width="1122" height="1402" alt="${esc(value('u.bannerAlt'))}" data-i18n-alt="u.bannerAlt"></div>`)+enquiry('instructor')},
 'booking':{title:'booking.page_title',desc:'u.separateCalendars',body:hero('booking.hero_badge','u.chooseClinic','u.separateCalendars',buttons())+section('booking.s1_eyebrow','u.chooseClinic',clinicCards())+section('booking.s1_eyebrow','booking.s1_title',`<div class="cards three">${[1,2,3].map(i=>`<article class="card"><span class="number">0${i}</span>${t('booking.card'+i+'_title','h3')}${t(i===2?'booking.card2_text':'u.bookingStep'+i,'p')}</article>`).join('')}</div>`)+section('booking.s2_eyebrow','booking.s2_title',`<div class="booking-grid">${hours()}<article class="card">${t('booking.info_maccabi_label','h2')}${t('booking.info_maccabi_value','p')}${t('u.bookingCopy','p')}${link('contact.html','nav.contact','button outline')}</article></div>`,'hours','soft')+section('m.contact.eyebrow','u.contactTitle',contacts())},
 'contact':{title:'nav.contact',desc:'m.contact.desc',body:hero('nav.contact','u.contactTitle','m.contact.desc',`<div class="actions">${link('https://wa.me/972544020043','m.contact.whatsapp','button','target="_blank" rel="noopener noreferrer"')}${link('mailto:magickids@magickidsinstitute.com','m.contact.mail','button outline')}</div>`)+section('m.contact.eyebrow','nav.contact',contacts())+section('booking.s1_eyebrow','booking.hours_title',`<div class="booking-grid">${hours()}<article class="card">${t('contact.address_value','h3')}${t('u.bookingCopy','p')}${link('booking.html','nav.booking')}</article></div>`,'hours','soft')},
 'workshop-register':{title:'u.workshopNew',desc:'u.workshopCopy',body:hero('m.workshop.eyebrow','m.workshop.title','u.workshopCopy',link('#enquiry','u.activityInterest'))+section('m.workshop.eyebrow','u.workshopNew',`${t('u.workshopNotice','p','class="notice"')}<div class="cards three">${[1,2,3].map(i=>`<article class="card"><span class="number">0${i}</span>${t('u.workshop'+i,'h3')}</article>`).join('')}</div>`)+enquiry('workshop')},
 'doctors':{title:'u.teamTitle',desc:'u.teamCopy',body:hero('m.director.line','u.teamTitle','u.teamCopy',link('about.html','hero.director'),true)+recruitStrip()},
 'app':{title:'u.app',desc:'u.installCopy',body:appBody},
 'clinicflow':{title:'u.app',desc:'u.installCopy',canonical:'app',body:appBody},
 'offline':{title:'u.offlineTitle',desc:'u.offlineCopy',noindex:true,body:hero('header.logo_name','u.offlineTitle','u.offlineCopy',link('index.html','u.retry'))+section('m.contact.eyebrow','nav.contact',contacts())},
 '404':{title:'u.404',desc:'u.404copy',noindex:true,body:hero('header.logo_name','u.404','u.404copy',link('index.html','u.back'))}
};
const nav=[['index','nav.home'],['treatments','nav.treatments'],['activities','m.nav.activities'],['about','nav.about'],['recruit','m.nav.join'],['contact','nav.contact']];
const configContext={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'site-config.js'),'utf8'),configContext);const verification=configContext.window.MAGIC_SITE?.google?.searchConsoleVerification||'';
const early=`(function(){var q=new URLSearchParams(location.search).get('lang'),l='ar';try{l=localStorage.getItem('magic-language')||l}catch(e){}if(['he','ar','en'].includes(q))l=q;if(!['he','ar','en'].includes(l))l='ar';document.documentElement.lang=l;document.documentElement.dir=l==='en'?'ltr':'rtl';window.magicLanguage=l})();`;
function documentFor(id,page){return `<!doctype html>
<html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#075a5d"><title>${esc(value(page.title))} | Magic Kids Institute</title><meta name="description" content="${esc(value(page.desc))}"><meta name="referrer" content="strict-origin-when-cross-origin"><link rel="canonical" href="${origin}/${page.canonical||id}.html">${page.noindex?'<meta name="robots" content="noindex,follow">':''}${verification?`<meta name="google-site-verification" content="${esc(verification)}">`:''}<meta property="og:title" content="${esc(value(page.title))}"><meta property="og:description" content="${esc(value(page.desc))}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}/${page.canonical||id}.html"><meta property="og:image" content="${origin}/assets/institute-logo.jpg"><link rel="icon" href="/assets/institute-logo.jpg"><link rel="apple-touch-icon" href="/assets/app-icon-192.png"><link rel="manifest" href="/manifest.webmanifest"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="Magic Kids"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700;800;900&family=Noto+Sans+Arabic:wght@400;500;600;700;800&display=swap" rel="stylesheet"><script>${early}</script><link rel="stylesheet" href="/brand.css?v=${version}"><script defer src="/site-text.js?v=${version}"></script><script defer src="/site-config.js?v=${version}"></script><script defer src="/app.js?v=${version}"></script><script defer src="/connect.js?v=${version}"></script></head>
<body data-page="${id}" data-title-key="${page.title}" data-description-key="${page.desc}"><a class="skip-link" href="#main">${t('skip')}</a><header class="site-header"><div class="header-inner"><a class="brand" href="/index.html"><img src="/assets/institute-logo.jpg" width="64" height="64" alt="${esc(value('u.logo'))}" data-i18n-alt="u.logo"><span>${t('header.logo_name','b')}<small>MAGIC KIDS INSTITUTE</small></span></a><nav class="main-nav" id="main-nav" aria-label="${esc(value('u.menu'))}" data-i18n-aria="u.menu">${nav.map(([url,key])=>`<a href="/${url}.html" ${url===id?'aria-current="page"':''}>${t(key)}</a>`).join('')}</nav><div class="header-actions"><div class="languages" role="group" aria-label="${esc(value('u.language'))}" data-i18n-aria="u.language"><button type="button" data-lang-switch="ar" lang="ar">العربية</button><button type="button" data-lang-switch="he" lang="he">עברית</button><button type="button" data-lang-switch="en" lang="en">EN</button></div><button class="menu-toggle" type="button" aria-controls="main-nav" aria-expanded="false">${t('u.menu')}<span aria-hidden="true">☰</span></button>${link('/booking.html','nav.booking','button header-book')}</div></div></header><main id="main">${page.body}</main><footer class="site-footer"><div class="wrap footer-grid"><div><a class="brand" href="/index.html"><img loading="lazy" src="/assets/institute-logo.jpg" width="64" height="64" alt=""><span>${t('header.logo_name','b')}<small lang="ar">معهد أطفال السحر</small></span></a>${t('u.tagline','p')}${t('contact.address_value','p')}</div><nav aria-label="${esc(value('footer.nav_title'))}" data-i18n-aria="footer.nav_title">${nav.concat([['adhd','nav.adhd'],['doctors','u.teamTitle'],['app','u.app']]).map(([url,key])=>`<a href="/${url}.html">${t(key)}</a>`).join('')}</nav><div class="footer-contact">${pediatricsPhones()}${t('u.instituteContact','b')}<a dir="ltr" href="https://wa.me/972544020043">054-402-0043</a><a dir="ltr" href="mailto:magickids@magickidsinstitute.com">magickids@magickidsinstitute.com</a>${link('https://magic-kids-hub.baseem-n.chatgpt.site/admin','u.staff','text-link')}${link('https://app.magickidsinstitute.com/admin/intake','u.adhdAdmin','text-link')}</div></div><div class="wrap footer-bottom footer__bottom">${t('footer.copy')}<a href="/app.html">${t('u.app')}</a></div></footer><div class="mobile-bar">${link('/booking.html','nav.booking','button')}${link('/activities.html','m.nav.activities','text-link')}${link('/app.html','u.app','text-link')}</div><dialog id="install-dialog" aria-labelledby="install-title"><div class="dialog-inner">${t('u.installHelp','h2','id="install-title"')}${t('u.ios','p')}${t('u.android','p')}<form method="dialog"><button class="button">${t('u.close')}</button></form></div></dialog></body></html>\n`;}
for(const [id,p] of Object.entries(pages))fs.writeFileSync(path.join(root,id+'.html'),documentFor(id,p));
const output={};for(const lang of languages){output[lang]={};for(const key of used)output[lang][key]=value(key,lang);}
// Runtime-only copy must be included even when not initially visible.
for(const key of ['u.installed','u.draftNote','u.invalidForm','u.recruitSubject','u.parentSubject','u.workshopSubject'])for(const lang of languages)output[lang][key]=value(key,lang);
fs.writeFileSync(path.join(root,'site-text.js'),'window.MAGIC_TRANSLATIONS = '+JSON.stringify(output)+';\n');
const manifest={id:'/',name:'Magic Kids Institute | معهد أطفال السحر',short_name:'Magic Kids',description:texts.ar['u.installCopy'],lang:'ar',dir:'rtl',start_url:'/index.html',scope:'/',display:'standalone',background_color:'#f6f8f8',theme_color:'#075a5d',icons:[192,512].map(s=>({src:'/assets/app-icon-'+s+'.png',sizes:s+'x'+s,type:'image/png',purpose:'any'})),shortcuts:[['booking','nav.booking'],['activities','m.nav.activities'],['recruit','m.path.join']].map(([route,key])=>({name:texts.ar[key],url:'/'+route+'.html'})),prefer_related_applications:false};
fs.writeFileSync(path.join(root,'manifest.webmanifest'),JSON.stringify(manifest,null,2)+'\n');
fs.writeFileSync(path.join(root,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+Object.entries(pages).filter(([,p])=>!p.noindex&&!p.canonical).map(([id])=>`<url><loc>${origin}/${id}.html</loc></url>`).join('')+'</urlset>\n');
console.log(`Built ${Object.keys(pages).length} pages with one template; ${Object.keys(output.ar).length} keys in all three languages.`);
