// Each entry has Hebrew, Arabic and English. All public copy is validated at build time.
export const copy = {
"p.title":["רפואה פרטית ואבחוני קשב", "طب خاص وتشخيص اضطراب الانتباه", "Private care and ADHD assessments"],
"p.desc":["מלאו פרטי קשר, בחרו שירות וקבלו תמחור לפני שליחת בקשה לתיאום.", "أدخلوا بيانات التواصل واختاروا الخدمة لعرض السعر قبل إرسال طلب التنسيق.", "Enter contact details and choose a service to see pricing before sending a request."],
"p.help":["לאחר מילוי הפרטים ולחיצה על הצגת תמחור, יוצגו המחירים. הבקשה תועבר רק לאחר שתשלחו אותה בוואטסאפ או במייל.", "بعد تعبئة التفاصيل والضغط على عرض الأسعار تظهر الأسعار. يُرسل الطلب فقط عند إرساله عبر واتساب أو البريد.", "Complete your details and select Show pricing. Your request is sent only when you send it in WhatsApp or email."],
"p.show":["הצגת תמחור", "عرض الأسعار", "Show pricing"],
"p.adhd":["אבחון קשב רפואי + MOXO בשני שלבים", "تشخيص طبي للانتباه + MOXO على مرحلتين", "Medical ADHD assessment + two-stage MOXO"],
"p.a1":["אבחון רפואי ומבדקים ללא תרופה ועם תרופה, לפי הוראת הרופא בלבד", "تشخيص طبي وفحص دون دواء ومع دواء، حسب تعليمات الطبيب فقط", "Medical assessment and testing without and with medication, only as directed by the doctor"],
"p.moxo":["מבדק MOXO בבית", "فحص MOXO من البيت", "MOXO from home"],
"p.m1":["מבדק ביתי בכפוף לאישור המכון", "فحص منزلي بموافقة المعهد", "Home assessment subject to institute approval"],
"p.pending":["הצעת מחיר אישית מהמכון — אין עדיין מחיר סופי", "عرض سعر شخصي من المعهد — لا يوجد سعر نهائي بعد", "Personal quote from the institute — final price pending"],
"p.distance":["מרחק משוער משפרעם (יאומת לפני אישור)", "المسافة التقريبية من شفاعمرو (تُراجع قبل التأكيد)", "Approximate distance from Shefa-Amr (verified before confirmation)"],
"p.d0":["עד 10 ק״מ", "حتى 10 كم", "Up to 10 km"],
"p.d1":["מעל 10 ועד 25 ק״מ", "أكثر من 10 وحتى 25 كم", "Over 10 and up to 25 km"],
"p.d2":["מעל 25 ק״מ", "أكثر من 25 كم", "Over 25 km"],
"p.night":["ביקור בית אחרי 20:00", "زيارة منزلية بعد 20:00", "Home visit after 20:00"],
"p.distanceNote":["מחירי הבסיס חלים עד 10 ק״מ משפרעם. מעל 10 ועד 25 ק״מ: תוספת 500 ₪. מעל 25 ק״מ: תוספת כוללת של 2,000 ₪ למרחק. אחרי 20:00: תוספת 500 ₪ בנוסף למרחק. התוספות לפני מע״מ; המחיר המוצג כולל מע״מ.", "الأسعار الأساسية حتى 10 كم من شفاعمرو. أكثر من 10 وحتى 25 كم: إضافة 500 ₪. أكثر من 25 كم: إضافة إجمالية للمسافة 2,000 ₪. بعد 20:00: إضافة 500 ₪ فوق إضافة المسافة. الإضافات قبل الضريبة؛ السعر المعروض شامل الضريبة.", "Base prices cover up to 10 km from Shefa-Amr. Over 10–25 km: add ₪500. Over 25 km: total distance surcharge ₪2,000. After 20:00: add ₪500 on top of the distance surcharge. Surcharges are before VAT; displayed prices include VAT."],
"p.approx":["מחיר משוער, כולל מע״מ", "سعر تقريبي شامل الضريبة", "Approximate price including VAT"],
"p.adhdNote":["החבילה כוללת אבחון רפואי ושני שלבי MOXO, ללא תרופה ועם תרופה, לפי ההערכה הרפואית. אין להתחיל, להפסיק או לשנות תרופה ללא הוראה אישית מהרופא.", "تشمل الحزمة تشخيصًا طبيًا ومرحلتي MOXO، دون دواء ومع دواء، حسب التقييم الطبي. لا تبدأوا دواءً أو توقفوه أو تغيّروه دون تعليمات شخصية من الطبيب.", "The package includes medical assessment and two MOXO stages, without and with medication, according to medical assessment. Do not start, stop or change medication without personal instructions from the doctor."],
"hm.title":["מבדק MOXO מהבית", "فحص MOXO من البيت", "MOXO assessment from home"],
"hm.desc":["בקשה למבדק ממוחשב מהבית, בתיאום עם צוות המכון ובאמצעות מחשב.", "طلب فحص محوسب من البيت، بالتنسيق مع فريق المعهد وباستخدام حاسوب.", "Request a computer-based home assessment coordinated with institute staff."],
"hm.techTitle":["מה צריך להכין?", "ماذا يجب تحضيره؟", "What to prepare"],
"hm.tech":["מחשב נייח או נייד, מקלדת תקינה, אינטרנט יציב ורמקולים תקינים. מומלץ Chrome; רזולוציית המסך לפחות 1024×768. פותחים את הקישור במחשב, לא בטלפון.", "حاسوب مكتبي أو محمول، لوحة مفاتيح سليمة، إنترنت مستقر ومكبّرات صوت تعمل. يُنصح بمتصفح Chrome ودقة شاشة 1024×768 على الأقل. افتحوا الرابط بالحاسوب وليس بالهاتف.", "Use a desktop or laptop, working keyboard, stable internet and speakers. Chrome is recommended; minimum screen resolution is 1024×768. Open the link on a computer, not a phone."],
"hm.roomTitle":["סביבת ביצוע מתאימה", "بيئة مناسبة للفحص", "A suitable testing environment"],
"hm.room":["בחרו חדר שקט ומואר, שולחן וכיסא נוחים. כבו טלוויזיה והתראות והרחיקו טלפונים. מנעו כניסות והפרעות; אין לכוון לתשובות או לסייע בלחיצות. ליווי ילד ייעשה לפי הנחיות המכון. דווחו על עייפות חריגה, מחלה, הפרעה או תקלה — הצוות יקבע אם ניתן לפרש את התוצאה.", "اختاروا غرفة هادئة ومضاءة وطاولة وكرسيًا مريحين. أطفئوا التلفاز والإشعارات وأبعدوا الهواتف. امنعوا المقاطعات ولا توجّهوا الإجابات أو تساعدوا بالضغط. مرافقة الطفل حسب تعليمات المعهد. أبلغوا عن تعب غير معتاد أو مرض أو مقاطعة أو عطل؛ الفريق يقرّر مدى قابلية تفسير النتيجة.", "Choose a quiet, well-lit room with a comfortable desk and chair. Turn off TV and notifications and put phones away. Prevent interruptions; do not coach responses or help with key presses. Follow staff instructions for supervising children. Report unusual fatigue, illness, interruptions or technical problems; staff will assess whether results can be interpreted."],
"hm.limits":["הכנה מתאימה תומכת בתנאי ביצוע עקביים אך אינה מבטיחה אמינות. MOXO הוא כלי עזר ואינו מחליף אבחון רפואי. אין לשנות טיפול תרופתי לקראת המבדק ללא הנחיה אישית.", "التحضير المناسب يدعم ثبات ظروف الفحص لكنه لا يضمن الموثوقية. MOXO أداة مساعدة ولا يحلّ محل التشخيص الطبي. لا تغيّروا العلاج الدوائي دون تعليمات شخصية.", "Preparation supports consistent conditions but does not guarantee reliability. MOXO supports, and does not replace, medical assessment. Do not change medication without personal instructions."],
"hm.flowTitle":["איך מתקדמים?", "كيف نتابع؟", "Next steps"],
"hm.step1":["ממלאים בקשה; הצוות בודק התאמה לביצוע ביתי ומתאם הנחיות.", "تُعبّأ الاستمارة؛ يراجع الفريق ملاءمة الفحص المنزلي وينسّق التعليمات.", "Submit a request; staff reviews suitability for home testing and coordinates instructions."],
"hm.step2":["עלות משוערת: 800 ₪ + מע״מ 18% — כ־944 ₪ בסך הכול. התשלום מתואם מול המכון; אין סליקה בדף זה.", "التكلفة التقريبية: 800 ₪ + ضريبة 18% — نحو 944 ₪ إجمالًا. يُنسّق الدفع مع المعهد؛ لا يوجد دفع في هذه الصفحة.", "Estimated cost: ₪800 plus 18% VAT — approximately ₪944 total. Arrange payment with the institute; this page does not process payments."],
"hm.step3":["לאחר אימות התשלום, צוות המכון יסדיר שליחת קישור אישי לפתיחה במחשב. שליחת בקשה לבדה אינה מפיקה קישור.", "بعد التحقّق من الدفع، ينسّق فريق المعهد إرسال رابط شخصي لفتحه بالحاسوب. تقديم الطلب وحده لا يُصدر رابطًا.", "After payment verification, institute staff arranges a personal link to open on a computer. Submitting a request alone does not issue a link."],
"hm.step4":["מבצעים לפי ההנחיות; התוצאות מועברות לפרשנות מקצועית.", "يُجرى الفحص حسب التعليمات وتُحال النتائج للتفسير المهني.", "Complete the assessment as instructed; results undergo professional interpretation."],
"hm.request":["בקשה למבדק MOXO בבית", "طلب فحص MOXO منزلي", "Request home MOXO"],

 'u.youtubeChannel':['ערוץ המכון','قناة المعهد','Institute channel'],
 'u.youtubeLabel':['ערוץ היוטיוב של המכון — נפתח בלשונית חדשה','قناة المعهد على يوتيوب — تفتح في علامة تبويب جديدة','Institute YouTube channel — opens in a new tab'],
 'u.dashboardEntry':['כניסה לדאשבורד','الدخول إلى لوحة الإدارة','Open dashboard'],
 'u.bookOne':['קביעת תור','حجز موعد','Book an appointment'],
 'u.bookQuestion':['איזה תור תרצו לקבוע?','أي موعد ترغبون بحجزه؟','Which appointment would you like?'],
 'booking.card3_title':["מקבלים אישור", "تأكيد الحجز", "Receive confirmation"],
 'booking.card2_text':["ממלאים את פרטי הילד/ה וההורה ומאשרים את ההזמנה.", "أكملوا تفاصيل الطفل وولي الأمر وأكّدوا الحجز.", "Enter the child and parent details, then confirm the booking."],
 'booking.card2_title':["ממלאים פרטים", "إكمال التفاصيل", "Enter your details"],
 'booking.card1_title':["בוחרים מועד", "اختيار موعد", "Choose a time"],
 'u.treatmentRequest':['פנייה לטיפול במכון','طلب علاج في المعهد','Request institute treatment'],
 'u.treatmentAdmin':['ניהול פניות לטיפול','إدارة طلبات العلاج','Manage treatment requests'],
 'u.treatmentFlow':['לטיפול במכון או לחוג: בוחרים סוג טיפול וממלאים טופס. הפנייה נשמרת במכון והצוות מתאם תור לפי סדר הפניות וזמינות המטפל/ת. שליחת הטופס אינה אישור לתור.','للعلاج في المعهد أو للدورات: اختاروا نوع العلاج واملؤوا النموذج. يُحفظ الطلب لدى المعهد ويتواصل الفريق لتنسيق الموعد حسب ترتيب الطلبات وتوفر المعالج/ة. إرسال النموذج ليس تأكيدًا للموعد.','For institute treatments or classes, choose a service and submit the form. The institute stores your request and staff schedules by request order and therapist availability. Submission does not confirm an appointment.'],

"p.nav":["רפואה פרטית", "طب خاص", "Private care"],
"p.cta":["בקשת ביקור בית או ייעוץ פרטי", "طلب زيارة منزلية أو استشارة خاصة", "Request private care"],
"p.home":["בדיקת תינוק בבית", "فحص الرضيع في البيت", "Baby examination at home"],
"p.phone":["ייעוץ טלפוני פרטי", "استشارة هاتفية خاصة", "Private phone consultation"],
"p.h1":["הגעה בתוך שעה", "الوصول خلال ساعة", "Arrival within 1 hour"],
"p.h2":["הגעה בתוך שעתיים", "الوصول خلال ساعتين", "Arrival within 2 hours"],
"p.h3":["הגעה בתוך 3–6 שעות", "الوصول خلال 3–6 ساعات", "Arrival within 3–6 hours"],
"p.t1":["שיחה בתוך שעה", "مكالمة خلال ساعة", "Call within 1 hour"],
"p.t2":["שיחה בתוך 2–3 שעות", "مكالمة خلال 2–3 ساعات", "Call within 2–3 hours"],
"p.t3":["המתנה של 4 שעות ומעלה", "انتظار 4 ساعات أو أكثر", "Wait of 4 hours or more"],
"p.total":["סה״כ כולל מע״מ", "المجموع شامل الضريبة", "Total including VAT"],
"p.base":["לפני מע״מ", "قبل الضريبة", "Before VAT"],
"p.vat":["מע״מ 18%", "ضريبة 18%", "18% VAT"],
"p.times":["הזמנים הם חלונות המתנה מבוקשים להגעה או לשיחה, ולא משך הבדיקה. הזמינות, אזור השירות והמועד טעונים אישור אישי; שליחת בקשה אינה מבטיחה מענה בחלון שבחרתם.", "الأوقات هي فترات انتظار مطلوبة للوصول أو الاتصال وليست مدة الفحص. التوفّر ومنطقة الخدمة والموعد تحتاج تأكيدًا شخصيًا؛ إرسال الطلب لا يضمن الاستجابة ضمن الفترة المختارة.", "Times are requested waiting windows for arrival or a call, not examination duration. Availability, coverage and timing require personal confirmation; a request does not guarantee the chosen window."],
"p.request":["פרטי הבקשה", "تفاصيل الطلب", "Request details"],
"p.city":["יישוב לביקור הבית", "البلدة للزيارة المنزلية", "Town for the home visit"],
"p.contact":["שם ההורה או איש הקשר", "اسم ولي الأمر أو جهة الاتصال", "Parent or contact name"],
"p.quote":["הצעת המחיר שלכם", "عرض السعر الخاص بكم", "Your quote"],
"p.note":["המחיר מתייחס לשירות ולחלון ההמתנה שנבחרו. אין חיוב באתר. ההזמנה מושלמת רק לאחר אישור הרופא והסכמתכם למחיר ולמועד.", "السعر للخدمة وفترة الانتظار المختارتين. لا يتم الدفع بالموقع. يكتمل الحجز فقط بعد موافقة الطبيب وموافقتكم على السعر والموعد.", "The quote covers the chosen service and waiting window. No payment is taken here. Booking is completed only after the doctor confirms and you agree to the price and time."],
"p.privacy":["לצורך הבקשה דרושים רק פרטי קשר ויישוב. כתובת מדויקת ופרטים רפואיים יתואמו ישירות בהמשך.", "للطلب نحتاج فقط بيانات التواصل والبلدة. يتم تنسيق العنوان الدقيق والتفاصيل الطبية مباشرة لاحقًا.", "Only contact details and a town are needed now. Arrange the exact address and medical details directly later."],
"p.ack":["הבנתי שזו בקשת תיאום ולא תור מאושר.", "أفهم أن هذا طلب تنسيق وليس موعدًا مؤكّدًا.", "I understand this is a coordination request, not a confirmed appointment."],
"p.wa":["פתיחת בקשה בוואטסאפ", "فتح الطلب في واتساب", "Open request in WhatsApp"],
"p.email":["פתיחת בקשה במייל", "فتح الطلب بالبريد الإلكتروني", "Open request in email"],
"p.draft":["נפתחה טיוטת בקשה. יש להשלים את השליחה בוואטסאפ או במייל. הבקשה אינה נשמרת באתר ואינה מאשרת תור.", "تم فتح مسوّدة الطلب. أكملوا الإرسال في واتساب أو البريد. الطلب لا يُحفظ بالموقع ولا يؤكّد موعدًا.", "A draft was opened. Complete sending in WhatsApp or email. This request is not stored on the website and does not confirm an appointment."],
"p.emergency":["השירות אינו מוקד חירום. במקרה חירום התקשרו למד״א 101; אין להמתין לאישור הבקשה.", "الخدمة ليست للطوارئ. في حالة طارئة اتصلوا بالإسعاف 101؛ لا تنتظروا تأكيد الطلب.", "This is not an emergency service. In an emergency call 101; do not wait for request confirmation."],
"p.nojs":["להגשת בקשה ללא הטופס: התקשרו למרפאה.", "لتقديم طلب دون النموذج: اتصلوا بالعيادة.", "To request care without the form, call the clinic."],

"f.title":["הידעתם? הגוף גדל — ההרגלים נשארים", "هل تعلمون؟ الجسم يكبر والعادات تستمر", "Did you know? Growing bodies, lasting habits"],
"f.tip":["רעיון קטן לבית", "فكرة صغيرة للبيت", "Try this at home"],
"f.source":["למקור המדעי", "المصدر العلمي", "Read the source"],
"f.pause":["עצירה", "إيقاف", "Pause"],
"f.play":["המשך", "متابعة", "Play"],
"f.next":["העובדה הבאה", "المعلومة التالية", "Next fact"],
"f.prev":["העובדה הקודמת", "المعلومة السابقة", "Previous fact"],
"f.0.title":["שינה היא חלק מהלמידה", "النوم جزء من التعلّم", "Sleep supports learning"],
"f.0.text":["שינה מספקת תומכת בקשב ובזיכרון. בגיל 6–12 מומלצות 9–12 שעות שינה ביממה.", "النوم الكافي يدعم الانتباه والذاكرة. بعمر 6–12 سنة يُنصح بنوم 9–12 ساعة يوميًا.", "Enough sleep supports attention and memory. Ages 6–12 need 9–12 hours per day."],
"f.0.tip":["קבעו שעת שינה קבועה ובחרו יחד סיפור קצר לסיום היום.", "حدّدوا وقت نوم ثابت واختاروا سوا قصة قصيرة لختام اليوم.", "Set a regular bedtime and choose a short story together."],
"f.1.title":["העצמות בונות עתודות לעתיד", "العظام تبني قوتها للمستقبل", "Bones build strength for the future"],
"f.1.text":["עצם היא רקמה חיה שמתחדשת. בילדות ובנעורים נבנית מסת עצם שתורמת לבריאות בהמשך החיים.", "العظم نسيج حي يتجدّد. في الطفولة والمراهقة تُبنى كتلة عظمية تساهم في صحة العظام لاحقًا.", "Bone is living tissue that renews itself. Childhood and adolescence build bone mass that supports later bone health."],
"f.1.tip":["שלבו משחק קפיצות או ריקוד שמתאים לגיל וליכולת, לצד תזונה מגוונת.", "جرّبوا لعبة قفز أو رقص مناسبة للعمر والقدرة، مع غذاء متنوّع.", "Try age- and ability-appropriate hopping or dancing alongside a varied diet."],
"f.2.title":["השמיעה זקוקה להגנה בכל גיל", "السمع يحتاج حماية بكل عمر", "Protect hearing at every age"],
"f.2.text":["רעש חזק או ממושך עלול להזיק לשמיעה, ולעיתים הנזק קבוע. גם ילדים ובני נוער עלולים להיפגע.", "الصوت العالي أو المستمر قد يضرّ السمع، وأحيانًا يكون الضرر دائمًا. الأطفال والمراهقون أيضًا معرّضون له.", "Loud or prolonged noise can harm hearing, sometimes permanently. Children and teenagers can be affected too."],
"f.2.tip":["בדקו יחד את עוצמת האוזניות והנמיכו אותה; התרחקו ממקור רעש חזק.", "افحصوا سوا مستوى صوت السماعات وخفّضوه، وابتعدوا عن مصدر الضجيج العالي.", "Check headphone volume together, turn it down and move away from loud noise."],
"f.3.title":["תנועה לא חייבת להיות חוג ספורט", "الحركة مش لازم تكون حصة رياضة", "Movement is more than organized sport"],
"f.3.text":["משחק פעיל, הליכה וריקוד הם פעילות גופנית. לילדים ולנוער חשובה תנועה יומיומית.", "اللعب النشيط والمشي والرقص كلها نشاط بدني. الحركة اليومية مهمة للأطفال والمراهقين.", "Active play, walking and dancing all count as physical activity. Daily movement matters for children and teenagers."],
"f.3.tip":["התחילו בהליכה משפחתית קצרה או בשיר אחד של ריקוד, והוסיפו עוד תנועה לאורך היום.", "ابدؤوا بمشوار عائلي قصير أو رقصة على أغنية، وزيدوا الحركة خلال اليوم.", "Start with a short family walk or one dance song, then add more movement through the day."],
"f.4.title":["רגעים פשוטים תומכים בהתפתחות", "لحظات بسيطة تدعم التطوّر", "Everyday moments support development"],
"f.4.text":["משחק, קריאה ושיחה עם ההורים תומכים בהתפתחות בריאה. לא כל למידה דורשת צעצוע מיוחד.", "اللعب والقراءة والحوار مع الأهل تدعم التطوّر السليم. التعلّم مش دايمًا بحاجة للعبة خاصة.", "Playing, reading and talking with parents support healthy development. Learning need not require special toys."],
"f.4.tip":["הביטו יחד בתמונה ושאלו: מה אתה רואה? הקשיבו לתשובה ותנו לשיחה להתפתח.", "تطلّعوا سوا على صورة واسألوا: شو شايف؟ اسمعوا الجواب وخلّوا الحوار يكمل.", "Look at a picture together and ask: What do you see? Listen and let the conversation grow."],
"f.5.title":["גם מתבגרים עדיין צריכים הרבה שינה", "حتى المراهقين بحاجة لنوم كافٍ", "Teenagers still need plenty of sleep"],
"f.5.text":["בגיל 13–17 מומלצות 8–10 שעות שינה ביממה; בגיל 18–60 מומלצות לפחות 7 שעות. הצורך משתנה עם הגיל.", "بعمر 13–17 سنة يُنصح بنوم 8–10 ساعات يوميًا؛ وبعمر 18–60 سنة، 7 ساعات على الأقل. الحاجة تتغيّر مع العمر.", "Ages 13–17 need 8–10 hours of sleep daily; adults aged 18–60 need at least 7 hours. Sleep needs change with age."],
"f.5.tip":["צרו הרגל משפחתי: מכבים מסכים לפחות חצי שעה לפני השינה — גם ההורים.", "اعملوا عادة عائلية: نطفّي الشاشات قبل النوم بنص ساعة على الأقل، والأهل كمان.", "Make it a family habit: turn off screens at least half an hour before bedtime, parents too."],

 "u.travelInsurance":["ביטוח נסיעות לחו״ל", "تأمين السفر للخارج", "Travel insurance"],
 "u.insuranceHint":["לרכישה ב־PassportCard · שפרעם לביטוח", "للشراء عبر PassportCard · شفاعمرو للتأمين", "Buy with PassportCard · Shfaram Insurance"],
 "u.esim":["חיבור eSIM לחו״ל", "اتصال eSIM للسفر", "Travel eSIM"],
 "u.comingSoon":["בקרוב", "قريبًا", "Coming soon"],
 "u.mksStore":["חנות המשחקים של MKS", "متجر ألعاب MKS", "MKS toy store"],
 "u.mksAccess":["כניסה לחנות · לפי הרשאות גישה", "دخول المتجر · حسب صلاحيات الوصول", "Open store · access permissions apply"],
 "u.quickServices":["עוד מבית ילדי הקסם", "المزيد من أطفال السحر", "More from Magic Kids"],

 'u.moxoTitle':['מבדק MOXO במכון ילדי הקסם','فحص MOXO في معهد أطفال السحر','MOXO at Magic Kids Institute'],
 'u.moxoBook':['בקשת תור למבדק MOXO','طلب موعد لفحص MOXO','Request a MOXO appointment'],
 'u.moxoWhat':['MOXO הוא מבדק קשב ממוחשב הכולל מסיחים חזותיים ושמיעתיים. הוא מסייע לאיש המקצוע בהערכת הקשב כחלק מתהליך אבחון, ואינו מחליף הערכה קלינית.','MOXO هو فحص انتباه محوسب يتضمن مشتّتات بصرية وسمعية. يساعد المختص في تقييم الانتباه ضمن عملية التشخيص، ولا يحلّ محل التقييم السريري.','MOXO is a computerized attention assessment with visual and auditory distractions. It supports professional assessment as part of the diagnostic process and does not replace clinical evaluation.'],
 'u.moxoHow':['כיצד מתבצע המבדק?','كيف يُجرى الفحص؟','How does the assessment work?'],
 'u.moxoSteps':['מקבלים הסבר ותרגול, ואז מבצעים משימה מול מחשב עם מקלדת ושמע בסביבה שקטה. התהליך כולל ההדרכה והתרגול נמשך עד כ־30 דקות. איש המקצוע עובר על התוצאות ומסביר אותן.','تتلقّون شرحًا وتدريبًا، ثم تنفّذون مهمة أمام حاسوب بلوحة مفاتيح وصوت في مكان هادئ. تستغرق العملية مع التعليمات والتدريب حتى نحو 30 دقيقة. يراجع المختص النتائج ويشرحها.','After instructions and practice, you complete a computer task using a keyboard and audio in a quiet setting. Including instructions and practice, the process takes up to about 30 minutes. A professional reviews and explains the results.'],
 'u.moxoApproval':['השאירו בקשה ויום מועדף. המועד ייקבע רק לאחר אישור המכון, ואז תישלח הודעת WhatsApp למספר שמסרתם.','اتركوا طلبًا ويومًا مفضّلًا. يُحدّد الموعد فقط بعد موافقة المعهد، ثم تُرسل رسالة واتساب إلى الرقم الذي أدخلتموه.','Submit a request and preferred day. Your appointment requires institute approval, followed by a WhatsApp confirmation to the number you provide.'],
 'u.moxoSource':['מידע מאתר MOXO הרשמי','معلومات من موقع MOXO الرسمي','Official MOXO information'],
 'u.sarahPolicy':['שרה, מזכירת המכון: תור לאבחון ניתן לקבוע רק לאחר שההורים והמורה השלימו ושלחו את השאלונים. אבחונים ביום רביעי בשעות 16:00, 17:00, 18:00 ו־19:00; כל אבחון נמשך שעה.','سارة، سكرتيرة المعهد: يمكن حجز التشخيص فقط بعد أن يُكمل الأهل والمعلم الاستبيانات ويرسلوها. المواعيد يوم الأربعاء في 16:00 و17:00 و18:00 و19:00؛ مدة كل تشخيص ساعة.','Sarah, the institute secretary, can schedule an assessment only after both parent and teacher questionnaires are fully submitted. Assessments are on Wednesdays at 16:00, 17:00, 18:00 and 19:00; each lasts one hour.'],

 'u.adminTitle':['כניסת אדמין','دخول الإدارة','Admin login'],
 'u.adminHelp':['לצוות המכון: יומני המרפאות, ניהול המכון ומעקב שאלונים. הכניסה בחשבון מורשה.','لطاقم المعهد: تقاويم العيادات وإدارة المعهد ومتابعة الاستبيانات. الدخول بحساب مخوّل.','For staff: clinic calendars, institute management and questionnaire tracking. Authorized account required.'],
 'u.adhdAdmin':['ניהול קליטה וזימון לקשב','إدارة ملفات ومواعيد عيادة الانتباه','ADHD intake and scheduling'],
 'u.pedsPhone':['WhatsApp מרפאת הילדים','واتساب عيادة الأطفال','Pediatrics clinic WhatsApp'],
 'u.pedsSecretary':['מזכירה בשעות פעילות המרפאה','السكرتيرة خلال ساعات عمل العيادة','Secretary during clinic opening hours'],
 'u.instituteContact':['יצירת קשר עם המכון','التواصل مع المعهد','Contact the institute'],
 'u.bookPeds':['תור למרפאת ילדים','حجز موعد لعيادة الأطفال','Book pediatrics'],
 'u.bookAdhd':['תור למרפאת קשב וריכוז','حجز موعد لعيادة الانتباه والتركيز','Book the ADHD clinic'],
 'u.chooseClinic':['בוחרים מרפאה, קובעים תור.','اختاروا العيادة واحجزوا موعدًا.','Choose your clinic. Book your visit.'],
 'u.separateCalendars':['לכל מרפאה יומן תורים נפרד. בחרו את השירות הרצוי כדי לראות את אפשרויות ההזמנה שלו.','لكل عيادة تقويم مواعيد مستقل. اختاروا الخدمة لعرض خيارات الحجز الخاصة بها.','Each clinic has its own appointment calendar. Choose the service to view its booking options.'],
 'u.pedsCalendar':['רפואת ילדים ומעקב במרפאה. פתיחת לוח התורים של מרפאת הילדים.','طب الأطفال والمتابعة في العيادة. افتحوا تقويم مواعيد عيادة الأطفال.','Pediatric care and clinic follow-ups. Open the pediatrics appointment calendar.'],
 'u.adhdCalendar':["מתחילים בפתיחת תיק, ממשיכים לשאלון הורים ושאלון מורה. כששניהם נשלחו, התיק עובר לצוות לתיאום פגישת אבחון.","ابدأوا بفتح ملف، ثم أكملوا استبيان الأهل واستبيان المعلم. بعد إرسال الاثنين، يظهر الملف للطاقم لتنسيق موعد التقييم.","Start with registration, then complete the parent and teacher questionnaires. Once both are submitted, the team can arrange your assessment appointment."],
 'u.bookingConfirmation':["פתיחת תיק או שליחת שאלון אינה אישור לתור. במרפאת הקשב מתאמים פגישה עם הצוות לאחר השלמת שני השאלונים. למרפאת הילדים אפשר לפנות גם בטלפונים המופיעים למעלה.","فتح الملف أو إرسال الاستبيان ليس تأكيداً للموعد. في عيادة الانتباه يُنسّق الموعد مع الطاقم بعد إكمال الاستبيانين. لعيادة الأطفال يمكن أيضاً الاتصال بالأرقام أعلاه.","Registration or questionnaire submission does not confirm an appointment. The ADHD team coordinates your visit after both questionnaires are complete. For pediatrics, you can also call the numbers above."],
 'u.hero1':['מקום לגדול.','مساحة للنمو.','Room to grow.'],
 'u.hero2':['מקום לגלות את הקסם.','ومكان لاكتشاف السحر.','A place to find the magic.'],
 'u.tagline':['ההבנה לפני האבחנה','الفهم قبل التشخيص','Understanding comes first'],
 'u.home':['הבית של ילדי הקסם','بيت أطفال السحر','The Magic Kids home'],
 'u.logo':['לוגו מכון ילדי הקסם','شعار معهد أطفال السحر','Magic Kids Institute logo'],
 'u.photo':['ד״ר בסים נמוז, מנהל המכון','الدكتور بسيم نموز، مدير المعهد','Dr. Basim Namouz, institute director'],
 'u.menu':['תפריט','القائمة','Menu'],
 'u.language':['שפת האתר','لغة الموقع','Website language'],
 'u.more':['לפרטים נוספים','للمزيد من التفاصيل','Learn more'],
 'u.back':['בחזרה לדף הבית','العودة للرئيسية','Back to home'],
 'u.app':['האפליקציה שלנו','تطبيق المعهد','Our app'],
 'u.staff':['כניסת צוות','دخول الطاقم','Staff sign in'],
 'u.allServices':['כל השירותים, במקום אחד.','كل الخدمات، في مكان واحد.','All our services, in one place.'],
 'u.servicesCopy':['רפואת ילדים, קשב וריכוז, ליווי הורים וחוגים. בוחרים תחום וממשיכים איתנו בדרך שמתאימה לכם.','طب أطفال، إصغاء وتركيز، إرشاد للأهل وأنشطة. اختاروا المجال لنرافقكم بالطريقة المناسبة لكم.','Pediatrics, ADHD assessment, parent guidance and activities. Find the right starting point for your family.'],
 'u.activityInterest':['מתעניינים בפעילות','مهتمّون بالنشاط','Ask about an activity'],
 'u.activityDetails':['גילים, מועדים, מחירים ומדריכים יפורסמו לאחר אישור הפעילות. כרגע אפשר לפנות לקבלת עדכון.','تُعلَن الأعمار والمواعيد والأسعار والمدرّبون بعد اعتماد النشاط. يمكنكم التواصل حاليًا للحصول على تحديث.','Ages, schedules, prices and instructors will be published once confirmed. Contact us for an update.'],
 'u.formTitle':['בואו נכיר','لنتعرّف','Let’s get acquainted'],
 'u.formHelp':['מלאו פרטי קשר של מבוגר ופתחו הודעה למכון. ההודעה תישלח רק לאחר שתשלחו אותה במייל או בוואטסאפ.','أدخلوا تفاصيل تواصل لشخص بالغ وافتحوا رسالة للمعهد. لن تُرسَل إلا بعد إرسالها من البريد أو واتساب.','Enter an adult’s contact details to prepare a message. It is sent only when you send it from your email or WhatsApp app.'],
 'u.name':['שם מלא של הפונה','الاسم الكامل لمقدّم الطلب','Your full name'],
 'u.phone':['טלפון לחזרה','رقم الهاتف للتواصل','Callback phone'],
 'u.email':['כתובת מייל','البريد الإلكتروني','Email address'],
 'u.subject':['תחום ההתעניינות','مجال الاهتمام','Area of interest'],
 'u.experience':['תחום, הכשרה וניסיון','المجال والتأهيل والخبرة','Field, qualifications and experience'],
 'u.message':['מה תרצו לשאול?','ماذا تودّون أن تسألوا؟','What would you like to ask?'],
 'u.optional':['רשות','اختياري','Optional'],
 'u.noMedical':['אין לצרף פרטים רפואיים או מסמכים בטופס זה.','يُرجى عدم إضافة معلومات أو مستندات طبية في هذا النموذج.','Please do not include medical details or documents in this form.'],
 'u.emailDraft':['פתיחת הודעה במייל','فتح رسالة بريد','Prepare an email'],
 'u.waDraft':['פתיחת הודעה בוואטסאפ','فتح رسالة واتساب','Prepare a WhatsApp message'],
 'u.draftNote':['ההודעה מוכנה. השלימו את השליחה באפליקציה שנפתחה. הפרטים לא נשמרו באתר.','الرسالة جاهزة. أكملوا الإرسال في التطبيق الذي فُتح. لم تُحفَظ التفاصيل في الموقع.','Your message is ready. Finish sending it in the app that opened. The website has not saved your details.'],
 'u.invalidForm':['בדקו את השם ואת מספר הטלפון לפני פתיחת ההודעה.','تحقّقوا من الاسم ورقم الهاتف قبل فتح الرسالة.','Check your name and phone number before preparing your message.'],
 'u.required':['שדות המסומנים בכוכבית הם חובה.','الحقول المعلّمة بنجمة مطلوبة.','Fields marked with an asterisk are required.'],
 'u.recruitSubject':['מועמדות להצטרפות למכון ילדי הקסם','طلب الانضمام لمعهد أطفال السحر','Application to join Magic Kids Institute'],
 'u.parentSubject':['התעניינות בפעילות במכון ילדי הקסם','استفسار عن نشاط في معهد أطفال السحر','Activity enquiry at Magic Kids Institute'],
 'u.workshopSubject':['התעניינות בסדנת הורים','استفسار عن ورشة للأهل','Parent workshop enquiry'],
 'u.applicationTitle':['הרעיון שלכם. המקום לצמוח.','فكرتكم. مساحة لتكبر.','Your idea. A place to grow.'],
 'u.recruitDetail':['נשמח להכיר מורי שחמט, מטפלים ומפעילי פעילויות מעניינות לילדים, לנוער, למבוגרים ולגיל השלישי.','يسعدنا التعرف إلى مدرّبي شطرنج ومعالجين ومقدّمي أنشطة جذّابة للأطفال والشباب والبالغين وكبار السن.','We welcome chess teachers, therapists and activity leaders for children, teens, adults and older adults.'],
 'u.recruitFit':['הכשרה מתאימה, גישה רגישה ויכולת להוביל קבוצה. אפשר להציע פעילות בעברית, בערבית או בשתי השפות.','تأهيل مناسب وتعامل حسّاس وقدرة على قيادة مجموعة. يمكن تقديم نشاط بالعربية أو العبرية أو كلتيهما.','Relevant training, a thoughtful approach and the ability to lead a group. Activities may be offered in Hebrew, Arabic or both.'],
 'u.bannerAlt':['מודעת גיוס למורי שחמט, מטפלים ומפעילי חוגים במכון ילדי הקסם','إعلان توظيف مدرّبي شطرنج ومعالجين ومقدّمي أنشطة في معهد أطفال السحر','Magic Kids recruitment poster for chess teachers, therapists and activity leaders'],
 'u.workshopNew':['המפגש הבא להורים','اللقاء القادم للأهل','The next parent workshop'],
 'u.workshopCopy':['סדנאות עם ד״ר בסים נמוז להבנת קשב וריכוז ולשאלות מחיי המשפחה. מועד ומחיר למפגש הבא יימסרו לאחר אישורם.','ورشات مع الدكتور بسيم نموز لفهم اضطراب الإصغاء والتركيز وأسئلة الحياة العائلية. سيُعلَن موعد وسعر اللقاء القادم بعد تأكيدهما.','Workshops with Dr. Basim Namouz about ADHD and family life. The next date and price will be shared once confirmed.'],
 'u.workshopNotice':['ההרשמה למפגש מ־19.4.2026 הסתיימה. אפשר לפנות לקבלת עדכון על סדנה נוספת.','انتهى التسجيل للقاء 19.4.2026. يمكنكم التواصل للحصول على تحديث عن ورشة قادمة.','Registration for the April 19, 2026 session has ended. Contact us for news of the next workshop.'],
 'u.workshop1':['להבין את קשיי הקשב','فهم صعوبات الإصغاء','Understanding attention difficulties'],
 'u.workshop2':['שאלות מהבית ומהמסגרת','أسئلة من البيت والإطار التعليمي','Questions from home and school'],
 'u.workshop3':['שיח וכלים להורים','حوار وأدوات للأهل','Discussion and tools for parents'],
 'u.installTitle':['ילדי הקסם. גם בטלפון שלכם.','أطفال السحر. على هاتفكم أيضًا.','Magic Kids. On your phone, too.'],
 'u.installCopy':['התקינו את אתר המכון כאפליקציה לגישה מהירה לשירותים, לחוגים ולתיאום תור — עם אותו מראה ואותה שפה.','ثبّتوا موقع المعهد كتطبيق للوصول السريع للخدمات والأنشطة وتنسيق المواعيد، بنفس التصميم واللغة.','Install the institute website as an app for quick access to services, activities and appointment requests, with the same design and language.'],
 'u.install':['התקנת האפליקציה','تثبيت التطبيق','Install the app'],
 'u.installHelp':['איך מוסיפים לטלפון?','كيف نضيفه للهاتف؟','How do I add it to my phone?'],
 'u.ios':['באייפון: פתחו את האתר ב־Safari, לחצו על שיתוף ובחרו ״הוסף למסך הבית״.','على آيفون: افتحوا الموقع في Safari، اضغطوا على المشاركة ثم «إضافة إلى الشاشة الرئيسية».','On iPhone: open this website in Safari, tap Share, then Add to Home Screen.'],
 'u.android':['באנדרואיד: פתחו ב־Chrome ובחרו בתפריט ״התקנת אפליקציה״ או ״הוספה למסך הבית״. אם כפתור ההתקנה מופיע כאן, אפשר להשתמש בו.','على أندرويد: افتحوا الموقع في Chrome واختاروا من القائمة «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية». يمكن استخدام زر التثبيت هنا عند ظهوره.','On Android: open in Chrome and choose Install app or Add to Home Screen in the menu. You can also use the install button here when available.'],
 'u.installed':['האפליקציה מותקנת במכשיר זה','التطبيق مثبّت على هذا الجهاز','The app is installed on this device'],
 'u.close':['סגירה','إغلاق','Close'],
 'u.appService1':['כל השירותים והחוגים','كل الخدمات والأنشطة','All services and activities'],
 'u.appService2':['פנייה מהירה למזכירה','تواصل سريع مع السكرتيرة','Contact the secretary'],
 'u.appService3':['עברית, ערבית ואנגלית','العربية والعبرية والإنجليزية','Arabic, Hebrew and English'],
 'u.appService4':['כניסה למרכז הניהול לצוות','دخول مركز الإدارة للطاقم','Staff management access'],
 'u.offlineTitle':['אתם כרגע ללא חיבור לאינטרנט','أنتم حاليًا غير متصلين بالإنترنت','You’re currently offline'],
 'u.offlineCopy':['פרטי הקשר זמינים כאן. התחברו מחדש כדי לפתוח עמודים מעודכנים או לשלוח פנייה.','تفاصيل التواصل متاحة هنا. أعيدوا الاتصال لفتح الصفحات المحدّثة أو إرسال رسالة.','Contact details are available here. Reconnect to open current pages or send an enquiry.'],
 'u.retry':['ניסיון נוסף','المحاولة مجددًا','Try again'],
 'u.appOffline':['פרטי קשר זמינים גם ללא אינטרנט. פתיחת עמודים מעודכנים ושליחת פניות דורשות חיבור.','تفاصيل التواصل متاحة أيضًا دون إنترنت. فتح الصفحات المحدّثة وإرسال الرسائل يحتاج إلى اتصال.','Contact details are also available offline. Current pages and sending enquiries require a connection.'],
 'u.bookingCopy':["בחרו שעה פנויה בקישור מרפאת הילדים והשלימו את הפרטים. לאחר אישור ההזמנה במסך התור נשמר ביומן, ללא אישור המזכירות. שמרו את הקישור האישי לביטול. אם לוח התורים אינו זמין, אפשר לפנות למרפאה.", "اختاروا وقتًا متاحًا في رابط عيادة الأطفال وأكملوا التفاصيل. بعد ظهور تأكيد الحجز يُحفظ الموعد دون موافقة السكرتارية. احفظوا رابط الإلغاء الشخصي. إذا كان التقويم غير متاح، تواصلوا مع العيادة.", "Choose an available time in the pediatrics booking link and complete your details. Once the confirmation appears, the appointment is saved without secretary approval. Save your personal cancellation link. If the calendar is unavailable, contact the clinic."],
 'u.bookingStep1':["נכנסים לקישור מרפאת הילדים ובוחרים יום ושעה פנויים.", "ادخلوا رابط عيادة الأطفال واختاروا يومًا ووقتًا متاحين.", "Open pediatrics booking and choose an available day and time."],
 'u.bookingStep3':["אישור ההזמנה מופיע במסך עם קישור אישי לביטול התור.", "يظهر تأكيد الحجز على الشاشة مع رابط شخصي لإلغاء الموعد.", "Confirmation appears on screen with a personal cancellation link."],
 'u.hoursNote':['שעות הקבלה המפורסמות באתר. יש לתאם ולאשר תור מול המזכירה.','ساعات الاستقبال المنشورة في الموقع. يُرجى تنسيق الموعد وتأكيده مع السكرتيرة.','The clinic’s published reception hours. Please arrange and confirm your visit with the secretary.'],
 'u.teamTitle':['אנשים שרואים את הילד.','طاقم يرى الطفل بكل جوانبه.','People who see the whole child.'],
 'u.teamCopy':['ד״ר בסים נמוז מוביל את המכון. אנו פועלים להרחבת הפעילות עם אנשי מקצוע ומדריכים נוספים; פרטי צוות חדשים יפורסמו לאחר אישורם.','يقود الدكتور بسيم نموز المعهد. نعمل على توسيع النشاط مع مختصّين ومدرّبين إضافيين؛ تُنشَر تفاصيل الطاقم الجديد بعد تأكيدها.','Dr. Basim Namouz leads the institute. We are developing activities with additional professionals and instructors; new team profiles will be published once confirmed.'],
 'u.contactTitle':['יש שאלה? אנחנו כאן.','لديكم سؤال؟ نحن هنا.','Have a question? We’re here.'],
 'u.404':['העמוד לא נמצא','الصفحة غير موجودة','Page not found'],
 'u.404copy':['אפשר להמשיך מהעמוד הראשי או לבחור שירות בתפריט.','يمكنكم المتابعة من الصفحة الرئيسية أو اختيار خدمة من القائمة.','Continue from the homepage or choose a service from the menu.']
};
export const activities = [
 ['chess','שחמט וחשיבה','شطرنج وتفكير','Chess and thinking','חשיבה קדימה, אסטרטגיה ומשחק.','تفكير للمستقبل واستراتيجيا ولعب.','Strategy, play and thinking ahead.'],
 ['robotics','רובוטיקה ובנייה','روبوتيكا وبناء','Robotics and building','בנייה, תכנון ופתרון אתגרים יחד.','بناء وتخطيط وحلّ التحدّيات معًا.','Build, plan and solve challenges together.'],
 ['art','אמנות ויצירה','فن وإبداع','Art and creativity','צבע, חומר ומרחב לדמיון אישי.','ألوان ومواد ومساحة للخيال الشخصي.','Colour, materials and room for imagination.'],
 ['music','מוזיקה ותנועה','موسيقى وحركة','Music and movement','קצב, צליל ותנועה בקבוצה.','إيقاع وصوت وحركة في مجموعة.','Rhythm, sound and movement together.'],
 ['young-science','מדענים צעירים','علماء صغار','Young scientists','סקרנות וניסויים בהנחיה.','فضول وتجارب بإرشاد المدرّب.','Curiosity and guided experiments.'],
 ['theatre','תיאטרון וביטוי','مسرح وتعبير','Theatre and expression','סיפורים, דמויות ומשחקי תפקידים.','قصص وشخصيات وتمثيل أدوار.','Stories, characters and role play.'],
 ['family','סדנאות בין־דוריות','ورشات بين الأجيال','Intergenerational workshops','זמן משותף לילדים, להורים ולסבים.','وقت مشترك للأطفال والأهل والأجداد.','Time together for children, parents and grandparents.'],
 ['therapist-groups','קבוצות בהנחיית מטפלים','مجموعات بإرشاد معالجين','Therapist-led groups','קבוצות בתכנון; ההתאמה תיקבע עם אנשי המקצוע.','مجموعات قيد التخطيط؛ تُحدّد الملاءمة مع المختصّين.','Groups in planning; suitability will be assessed with qualified professionals.']
];
