// Each entry has Hebrew, Arabic and English. All public copy is validated at build time.
export const copy = {
 'u.bookPeds':['תור למרפאת ילדים','حجز موعد لعيادة الأطفال','Book pediatrics'],
 'u.bookAdhd':['תור למרפאת קשב וריכוז','حجز موعد لعيادة الانتباه والتركيز','Book the ADHD clinic'],
 'u.chooseClinic':['בוחרים מרפאה, קובעים תור.','اختاروا العيادة واحجزوا موعدًا.','Choose your clinic. Book your visit.'],
 'u.separateCalendars':['לכל מרפאה יומן תורים נפרד. בחרו את השירות הרצוי כדי לראות את אפשרויות ההזמנה שלו.','لكل عيادة تقويم مواعيد مستقل. اختاروا الخدمة لعرض خيارات الحجز الخاصة بها.','Each clinic has its own appointment calendar. Choose the service to view its booking options.'],
 'u.pedsCalendar':['רפואת ילדים ומעקב במרפאה. פתיחת לוח התורים של מרפאת הילדים.','طب الأطفال والمتابعة في العيادة. افتحوا تقويم مواعيد عيادة الأطفال.','Pediatric care and clinic follow-ups. Open the pediatrics appointment calendar.'],
 'u.adhdCalendar':['אבחון קשב וריכוז. קביעת אבחון לאחר השלמת שאלוני ההורה והמורה.','تشخيص اضطراب الانتباه والتركيز. يُحجز موعد التشخيص بعد استكمال استبيانات الأهل والمعلم.','ADHD assessments. Book after completing the parent and teacher questionnaires.'],
 'u.bookingConfirmation':['תור נקבע רק לאחר שמופיע אישור הזמנה. אם ההזמנה המקוונת אינה זמינה, המזכירות תסייע בתיאום.','يُحجز الموعد فقط بعد ظهور تأكيد الحجز. إذا لم يتوفر الحجز الإلكتروني، تساعدكم السكرتارية في التنسيق.','Your appointment is booked only when a confirmation appears. If online booking is unavailable, the clinic can help you arrange a visit.'],
 'u.hero1':['מקום לגדול.','مساحة للنمو.','Room to grow.'],
 'u.hero2':['מקום לגלות את הקסם.','ومكان لاكتشاف السحر.','A place to find the magic.'],
 'u.tagline':['ההבנה לפני האבחנה','الفهم قبل التشخيص','Understanding comes first'],
 'u.home':['הבית של ילדי הקסם','بيت أطفال السحر','The Magic Kids home'],
 'u.logo':['לוגו מכון ילדי הקסם','شعار معهد أطفال السحر','Magic Kids Institute logo'],
 'u.photo':['ד״ר בסים נמוז, מנהל המכון','الدكتور بسيم نموز، مدير المعهد','Dr. Basim Namouz, institute director'],
 'u.menu':['תפריט','القائمة','Menu'],
 'u.language':['שפת האתר','لغة الموقع','Website language'],
 'u.more':['לפרטים נוספים','للمزيد من التفاصيل','Learn more'],
 'u.back':['בחזרה לדף הבית','العودة للرئيسية','Back to home'],
 'u.app':['האפליקציה שלנו','تطبيق المعهد','Our app'],
 'u.staff':['כניסת צוות','دخول الطاقم','Staff sign in'],
 'u.allServices':['כל השירותים, במקום אחד.','كل الخدمات، في مكان واحد.','All our services, in one place.'],
 'u.servicesCopy':['רפואת ילדים, קשב וריכוז, ליווי הורים וחוגים. בוחרים תחום וממשיכים איתנו בדרך שמתאימה לכם.','طب أطفال، إصغاء وتركيز، إرشاد للأهل وأنشطة. اختاروا المجال لنرافقكم بالطريقة المناسبة لكم.','Pediatrics, ADHD assessment, parent guidance and activities. Find the right starting point for your family.'],
 'u.activityInterest':['מתעניינים בפעילות','مهتمّون بالنشاط','Ask about an activity'],
 'u.activityDetails':['גילים, מועדים, מחירים ומדריכים יפורסמו לאחר אישור הפעילות. כרגע אפשר לפנות לקבלת עדכון.','تُعلَن الأعمار والمواعيد والأسعار والمدرّبون بعد اعتماد النشاط. يمكنكم التواصل حاليًا للحصول على تحديث.','Ages, schedules, prices and instructors will be published once confirmed. Contact us for an update.'],
 'u.formTitle':['בואו נכיר','لنتعرّف','Let’s get acquainted'],
 'u.formHelp':['מלאו פרטי קשר של מבוגר ופתחו הודעה למכון. ההודעה תישלח רק לאחר שתשלחו אותה במייל או בוואטסאפ.','أدخلوا تفاصيل تواصل لشخص بالغ وافتحوا رسالة للمعهد. لن تُرسَل إلا بعد إرسالها من البريد أو واتساب.','Enter an adult’s contact details to prepare a message. It is sent only when you send it from your email or WhatsApp app.'],
 'u.name':['שם מלא של הפונה','الاسم الكامل لمقدّم الطلب','Your full name'],
 'u.phone':['טלפון לחזרה','رقم الهاتف للتواصل','Callback phone'],
 'u.email':['כתובת מייל','البريد الإلكتروني','Email address'],
 'u.subject':['תחום ההתעניינות','مجال الاهتمام','Area of interest'],
 'u.experience':['תחום, הכשרה וניסיון','المجال والتأهيل والخبرة','Field, qualifications and experience'],
 'u.message':['מה תרצו לשאול?','ماذا تودّون أن تسألوا؟','What would you like to ask?'],
 'u.optional':['רשות','اختياري','Optional'],
 'u.noMedical':['אין לצרף פרטים רפואיים או מסמכים בטופס זה.','يُرجى عدم إضافة معلومات أو مستندات طبية في هذا النموذج.','Please do not include medical details or documents in this form.'],
 'u.emailDraft':['פתיחת הודעה במייל','فتح رسالة بريد','Prepare an email'],
 'u.waDraft':['פתיחת הודעה בוואטסאפ','فتح رسالة واتساب','Prepare a WhatsApp message'],
 'u.draftNote':['ההודעה מוכנה. השלימו את השליחה באפליקציה שנפתחה. הפרטים לא נשמרו באתר.','الرسالة جاهزة. أكملوا الإرسال في التطبيق الذي فُتح. لم تُحفَظ التفاصيل في الموقع.','Your message is ready. Finish sending it in the app that opened. The website has not saved your details.'],
 'u.invalidForm':['בדקו את השם ואת מספר הטלפון לפני פתיחת ההודעה.','تحقّقوا من الاسم ورقم الهاتف قبل فتح الرسالة.','Check your name and phone number before preparing your message.'],
 'u.required':['שדות המסומנים בכוכבית הם חובה.','الحقول المعلّمة بنجمة مطلوبة.','Fields marked with an asterisk are required.'],
 'u.recruitSubject':['מועמדות להצטרפות למכון ילדי הקסם','طلب الانضمام لمعهد أطفال السحر','Application to join Magic Kids Institute'],
 'u.parentSubject':['התעניינות בפעילות במכון ילדי הקסם','استفسار عن نشاط في معهد أطفال السحر','Activity enquiry at Magic Kids Institute'],
 'u.workshopSubject':['התעניינות בסדנת הורים','استفسار عن ورشة للأهل','Parent workshop enquiry'],
 'u.applicationTitle':['הרעיון שלכם. המקום לצמוח.','فكرتكم. مساحة لتكبر.','Your idea. A place to grow.'],
 'u.recruitDetail':['נשמח להכיר מורי שחמט, מטפלים ומפעילי פעילויות מעניינות לילדים, לנוער, למבוגרים ולגיל השלישי.','يسعدنا التعرف إلى مدرّبي شطرنج ومعالجين ومقدّمي أنشطة جذّابة للأطفال والشباب والبالغين وكبار السن.','We welcome chess teachers, therapists and activity leaders for children, teens, adults and older adults.'],
 'u.recruitFit':['הכשרה מתאימה, גישה רגישה ויכולת להוביל קבוצה. אפשר להציע פעילות בעברית, בערבית או בשתי השפות.','تأهيل مناسب وتعامل حسّاس وقدرة على قيادة مجموعة. يمكن تقديم نشاط بالعربية أو العبرية أو كلتيهما.','Relevant training, a thoughtful approach and the ability to lead a group. Activities may be offered in Hebrew, Arabic or both.'],
 'u.bannerAlt':['מודעת גיוס למורי שחמט, מטפלים ומפעילי חוגים במכון ילדי הקסם','إعلان توظيف مدرّبي شطرنج ومعالجين ومقدّمي أنشطة في معهد أطفال السحر','Magic Kids recruitment poster for chess teachers, therapists and activity leaders'],
 'u.workshopNew':['המפגש הבא להורים','اللقاء القادم للأهل','The next parent workshop'],
 'u.workshopCopy':['סדנאות עם ד״ר בסים נמוז להבנת קשב וריכוז ולשאלות מחיי המשפחה. מועד ומחיר למפגש הבא יימסרו לאחר אישורם.','ورشات مع الدكتور بسيم نموز لفهم اضطراب الإصغاء والتركيز وأسئلة الحياة العائلية. سيُعلَن موعد وسعر اللقاء القادم بعد تأكيدهما.','Workshops with Dr. Basim Namouz about ADHD and family life. The next date and price will be shared once confirmed.'],
 'u.workshopNotice':['ההרשמה למפגש מ־19.4.2026 הסתיימה. אפשר לפנות לקבלת עדכון על סדנה נוספת.','انتهى التسجيل للقاء 19.4.2026. يمكنكم التواصل للحصول على تحديث عن ورشة قادمة.','Registration for the April 19, 2026 session has ended. Contact us for news of the next workshop.'],
 'u.workshop1':['להבין את קשיי הקשב','فهم صعوبات الإصغاء','Understanding attention difficulties'],
 'u.workshop2':['שאלות מהבית ומהמסגרת','أسئلة من البيت والإطار التعليمي','Questions from home and school'],
 'u.workshop3':['שיח וכלים להורים','حوار وأدوات للأهل','Discussion and tools for parents'],
 'u.installTitle':['ילדי הקסם. גם בטלפון שלכם.','أطفال السحر. على هاتفكم أيضًا.','Magic Kids. On your phone, too.'],
 'u.installCopy':['התקינו את אתר המכון כאפליקציה לגישה מהירה לשירותים, לחוגים ולתיאום תור — עם אותו מראה ואותה שפה.','ثبّتوا موقع المعهد كتطبيق للوصول السريع للخدمات والأنشطة وتنسيق المواعيد، بنفس التصميم واللغة.','Install the institute website as an app for quick access to services, activities and appointment requests, with the same design and language.'],
 'u.install':['התקנת האפליקציה','تثبيت التطبيق','Install the app'],
 'u.installHelp':['איך מוסיפים לטלפון?','كيف نضيفه للهاتف؟','How do I add it to my phone?'],
 'u.ios':['באייפון: פתחו את האתר ב־Safari, לחצו על שיתוף ובחרו ״הוסף למסך הבית״.','على آيفون: افتحوا الموقع في Safari، اضغطوا على المشاركة ثم «إضافة إلى الشاشة الرئيسية».','On iPhone: open this website in Safari, tap Share, then Add to Home Screen.'],
 'u.android':['באנדרואיד: פתחו ב־Chrome ובחרו בתפריט ״התקנת אפליקציה״ או ״הוספה למסך הבית״. אם כפתור ההתקנה מופיע כאן, אפשר להשתמש בו.','على أندرويد: افتحوا الموقع في Chrome واختاروا من القائمة «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية». يمكن استخدام زر التثبيت هنا عند ظهوره.','On Android: open in Chrome and choose Install app or Add to Home Screen in the menu. You can also use the install button here when available.'],
 'u.installed':['האפליקציה מותקנת במכשיר זה','التطبيق مثبّت على هذا الجهاز','The app is installed on this device'],
 'u.close':['סגירה','إغلاق','Close'],
 'u.appService1':['כל השירותים והחוגים','كل الخدمات والأنشطة','All services and activities'],
 'u.appService2':['פנייה מהירה למזכירה','تواصل سريع مع السكرتيرة','Contact the secretary'],
 'u.appService3':['עברית, ערבית ואנגלית','العربية والعبرية والإنجليزية','Arabic, Hebrew and English'],
 'u.appService4':['כניסה למרכז הניהול לצוות','دخول مركز الإدارة للطاقم','Staff management access'],
 'u.offlineTitle':['אתם כרגע ללא חיבור לאינטרנט','أنتم حاليًا غير متصلين بالإنترنت','You’re currently offline'],
 'u.offlineCopy':['פרטי הקשר זמינים כאן. התחברו מחדש כדי לפתוח עמודים מעודכנים או לשלוח פנייה.','تفاصيل التواصل متاحة هنا. أعيدوا الاتصال لفتح الصفحات المحدّثة أو إرسال رسالة.','Contact details are available here. Reconnect to open current pages or send an enquiry.'],
 'u.retry':['ניסיון נוסף','المحاولة مجددًا','Try again'],
 'u.appOffline':['פרטי קשר זמינים גם ללא אינטרנט. פתיחת עמודים מעודכנים ושליחת פניות דורשות חיבור.','تفاصيل التواصل متاحة أيضًا دون إنترنت. فتح الصفحات المحدّثة وإرسال الرسائل يحتاج إلى اتصال.','Contact details are also available offline. Current pages and sending enquiries require a connection.'],
 'u.bookingCopy':['לתיאום ביקור במרפאת הילדים פונים למזכירה. היא תתאם איתכם את סוג הביקור והמועד ותאשר את התור.','لتنسيق زيارة لعيادة الأطفال، تواصلوا مع السكرتيرة لتحديد نوع الزيارة والموعد وتأكيد الحجز.','Contact the secretary to arrange a pediatric clinic visit. She will confirm the visit type, date and appointment.'],
 'u.bookingStep1':['פונים עם שם המבוגר ומספר לחזרה.','تواصلوا باسم الشخص البالغ ورقم للرد.','Send the adult contact name and a callback number.'],
 'u.bookingStep3':['המועד סופי רק לאחר אישור המרפאה.','يكون الموعد نهائيًا بعد تأكيد العيادة فقط.','Your appointment is final only after the clinic confirms it.'],
 'u.hoursNote':['שעות הקבלה המפורסמות באתר. יש לתאם ולאשר תור מול המזכירה.','ساعات الاستقبال المنشورة في الموقع. يُرجى تنسيق الموعد وتأكيده مع السكرتيرة.','The clinic’s published reception hours. Please arrange and confirm your visit with the secretary.'],
 'u.teamTitle':['אנשים שרואים את הילד.','طاقم يرى الطفل بكل جوانبه.','People who see the whole child.'],
 'u.teamCopy':['ד״ר בסים נמוז מוביל את המכון. אנו פועלים להרחבת הפעילות עם אנשי מקצוע ומדריכים נוספים; פרטי צוות חדשים יפורסמו לאחר אישורם.','يقود الدكتور بسيم نموز المعهد. نعمل على توسيع النشاط مع مختصّين ومدرّبين إضافيين؛ تُنشَر تفاصيل الطاقم الجديد بعد تأكيدها.','Dr. Basim Namouz leads the institute. We are developing activities with additional professionals and instructors; new team profiles will be published once confirmed.'],
 'u.contactTitle':['יש שאלה? אנחנו כאן.','لديكم سؤال؟ نحن هنا.','Have a question? We’re here.'],
 'u.404':['העמוד לא נמצא','الصفحة غير موجودة','Page not found'],
 'u.404copy':['אפשר להמשיך מהעמוד הראשי או לבחור שירות בתפריט.','يمكنكم المتابعة من الصفحة الرئيسية أو اختيار خدمة من القائمة.','Continue from the homepage or choose a service from the menu.']
};
export const activities = [
 ['chess','שחמט וחשיבה','شطرنج وتفكير','Chess and thinking','חשיבה קדימה, אסטרטגיה ומשחק.','تفكير للمستقبل واستراتيجيا ولعب.','Strategy, play and thinking ahead.'],
 ['robotics','רובוטיקה ובנייה','روبوتيكا وبناء','Robotics and building','בנייה, תכנון ופתרון אתגרים יחד.','بناء وتخطيط وحلّ التحدّيات معًا.','Build, plan and solve challenges together.'],
 ['art','אמנות ויצירה','فن وإبداع','Art and creativity','צבע, חומר ומרחב לדמיון אישי.','ألوان ومواد ومساحة للخيال الشخصي.','Colour, materials and room for imagination.'],
 ['music','מוזיקה ותנועה','موسيقى وحركة','Music and movement','קצב, צליל ותנועה בקבוצה.','إيقاع وصوت وحركة في مجموعة.','Rhythm, sound and movement together.'],
 ['young-science','מדענים צעירים','علماء صغار','Young scientists','סקרנות וניסויים בהנחיה.','فضول وتجارب بإرشاد المدرّب.','Curiosity and guided experiments.'],
 ['theatre','תיאטרון וביטוי','مسرح وتعبير','Theatre and expression','סיפורים, דמויות ומשחקי תפקידים.','قصص وشخصيات وتمثيل أدوار.','Stories, characters and role play.'],
 ['family','סדנאות בין־דוריות','ورشات بين الأجيال','Intergenerational workshops','זמן משותף לילדים, להורים ולסבים.','وقت مشترك للأطفال والأهل والأجداد.','Time together for children, parents and grandparents.'],
 ['therapist-groups','קבוצות בהנחיית מטפלים','مجموعات بإرشاد معالجين','Therapist-led groups','קבוצות בתכנון; ההתאמה תיקבע עם אנשי המקצוע.','مجموعات قيد التخطيط؛ تُحدّد الملاءمة مع المختصّين.','Groups in planning; suitability will be assessed with qualified professionals.']
];
